# Generated by Django 5.1.4 on 2025-04-09 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dry_run_import', 'Импорт для сравнения'), ('import', 'Импорт'), ('export', 'Экспорт')], max_length=14, verbose_name='Тип')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Параметры')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В процессе'), ('done', 'Завершено'), ('error', 'Ошибка'), ('aborted', 'Прервано')], default='new', max_length=10, verbose_name='Статус')),
                ('status_details', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('file', models.FileField(upload_to='task_attachments/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='taskmanager.task')),
            ],
            options={
                'unique_together': {('task', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('type', models.CharField(choices=[('file', 'Файл'), ('text', 'Текст'), ('json', 'JSON')], max_length=4, verbose_name='Тип')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='task_results/')),
                ('result_text', models.TextField(blank=True, null=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='taskmanager.task')),
            ],
            options={
                'unique_together': {('task', 'slug')},
            },
        ),
    ]
