# Generated by Django 5.1.4 on 2025-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dry_run',
            field=models.BooleanField(default=False, verbose_name='Dry Run'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('import', 'Импорт'), ('export', 'Экспорт')], max_length=6, verbose_name='Тип'),
        ),
    ]
