# Generated by Django 5.1.4 on 2025-04-10 04:28

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_task_dry_run_alter_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dry_run',
            field=models.BooleanField(blank=True, default=False, verbose_name='Dry Run'),
        ),
    ]
