image: alpine

variables:
  # нам не нужен вообще репозиторий в нашей сборке
  GIT_STRATEGY: none

before_script:
  - apk add openssh-client

  - eval $(ssh-agent -s)

  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ssh-keyscan 92.118.114.27 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy_ops:
  stage: deploy
  only:
  - main
  script:
  - ssh ops@92.118.114.27 "source /home/ops/witzenmann-ops/etc/profile.d/ops.sh; /home/ops/witzenmann-ops/etc/publish.sh --ci"
