# Generated by Django 4.1.7 on 2023-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
    ]
