# Generated by Django 4.1.7 on 2023-08-03 11:46

from django.db import migrations, models
import pybarker.django.contrib.auth.models


def populate_email_if_empty(apps, scheme_editor):
    from django.db.models import Q, F, Value
    from django.db.models.functions import Concat

    User = apps.get_model('kernel', 'User')

    users = User.objects.filter(
        Q(email__isnull=True) | Q(email='')
    ).update(email=Concat(F('username'), Value('@local')))


class Migration(migrations.Migration):
    dependencies = [
        ('kernel', '0004_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pybarker.django.contrib.auth.models.EmailedUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RunPython(populate_email_if_empty),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='crm_login',
            field=models.CharField(blank=True, help_text='Для внутреннего пользователя', max_length=255, null=True,
                                   verbose_name='Логин в CRM'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(
                choices=[('internal', 'Внутренний пользователь'), ('external', 'Внешний пользователь')],
                default='external', max_length=255, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
