# Generated by Django 4.1.7 on 2023-08-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Внешний идентификатор (CRM)')),
                ('inn', models.CharField(blank=True, max_length=64, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=64, null=True, verbose_name='КПП')),
                ('payment_bank', models.CharField(blank=True, max_length=128, null=True, verbose_name='Банк')),
                ('payment_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='Расс. счет')),
                ('bik', models.CharField(blank=True, max_length=64, null=True, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='Корр. счет')),
                ('file', models.FileField(blank=True, help_text='Свидетельство о регистрации', null=True, upload_to='', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='kernel.organization', verbose_name='Организация'),
        ),
    ]
