# Generated by Django 4.2 on 2023-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0006_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Конфигурация UI'),
        ),
    ]
