# Generated by Django 4.2 on 2023-10-05 08:29

from django.db import migrations
import pybarker.django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0007_user_ui_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ui_config',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Конфигурация UI'),
        ),
    ]
