# Generated by Django 4.2.7 on 2024-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0009_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(default='dPRDtweRWqcqRN8r3GFZ3p', max_length=32, unique=True, verbose_name='Токен'),
        ),
    ]
