# Generated by Django 4.2.7 on 2024-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0010_alter_apitoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(default='5kbDhcb4QwDDphP5LnAaT6', max_length=32, unique=True, verbose_name='Токен'),
        ),
    ]
