# Generated by Django 5.1.4 on 2025-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0011_alter_apitoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(max_length=32, unique=True, verbose_name='Токен'),
        ),
    ]
