# Generated by Django 5.1.4 on 2025-08-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kernel", "0012_apitoken_deleted_at_organization_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apitoken",
            options={
                "default_permissions": (),
                "ordering": ["user"],
                "permissions": (
                    ("view_apitoken", "Может просматривать API-токены пользователей"),
                    ("add_apitoken", "Может добавлять API-токены пользователей"),
                    ("change_apitoken", "Может изменять API-токены пользователей"),
                    ("delete_apitoken", "Может удалять API-токены пользователей"),
                ),
                "verbose_name": "API-токен",
                "verbose_name_plural": "API-токены",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "default_permissions": (),
                "permissions": (
                    ("view_organization", "Может просматривать организации"),
                    ("add_organization", "Может добавлять организации"),
                    ("change_organization", "Может изменять организации"),
                    ("delete_organization", "Может удалять организации"),
                ),
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": (),
                "ordering": ["email"],
                "permissions": (
                    ("view_user", "Может просматривать пользователей"),
                    ("add_user", "Может добавлять пользователей"),
                    ("change_user", "Может изменять пользователей"),
                    ("delete_user", "Может удалять пользователей"),
                ),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
