# Generated by Django 4.2 on 2023-08-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipeDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=32, verbose_name='DN')),
                ('designation', models.CharField(max_length=255, verbose_name='Обозначение диаметра')),
                ('mm_ru', models.FloatField(verbose_name='РФ')),
                ('mm_en', models.FloatField(verbose_name='EN')),
                ('mm_ruen', models.FloatField(verbose_name='РФ/EN')),
                ('mm_dn', models.FloatField(verbose_name='DN')),
            ],
            options={
                'verbose_name': 'диаметр трубы',
                'verbose_name_plural': 'диаметры труб',
                'ordering': ('dn',),
            },
        ),
    ]
