# Generated by Django 4.2 on 2023-08-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_populate_pipe_diameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipediameter',
            options={'verbose_name': 'диаметр трубы', 'verbose_name_plural': 'диаметры труб'},
        ),
    ]
