# Generated by Django 4.2 on 2023-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_pipediameter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgv', models.IntegerField(verbose_name='LGV')),
                ('kn', models.IntegerField(verbose_name='kN')),
            ],
            options={
                'verbose_name': 'нагрузочная группа',
                'verbose_name_plural': 'нагрузочные группы',
            },
        ),
    ]
