# Generated by Django 4.2 on 2023-09-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_populate_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='group',
            field=models.CharField(default='NONE', max_length=32, verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
