# Generated by Django 4.2 on 2023-10-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_material_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipediameter',
            old_name='mm_dn',
            new_name='dn_en',
        ),
        migrations.RemoveField(
            model_name='pipediameter',
            name='dn',
        ),
        migrations.RemoveField(
            model_name='pipediameter',
            name='mm_ruen',
        ),
    ]
