# Generated by Django 4.2 on 2023-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_mm_dn_pipediameter_dn_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipediameter',
            old_name='designation',
            new_name='dn_ru',
        ),
        migrations.AlterField(
            model_name='pipediameter',
            name='dn_en',
            field=models.CharField(max_length=255, verbose_name='Обозначение диаметра EN'),
        ),
    ]
