# Generated by Django 4.2 on 2023-10-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_designation_pipediameter_dn_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipediameter',
            name='dn_ru',
            field=models.CharField(max_length=255, verbose_name='Обозначение диаметра RU'),
        ),
    ]
