# Generated by Django 4.2 on 2023-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_nominaldiameter_newpipediameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveringType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип покрытия',
                'verbose_name_plural': 'типы покрытии',
            },
        ),
    ]
