# Generated by Django 4.2 on 2023-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_coveringtype'),
        ('ops', '0039_alter_attribute_catalog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipeDiameter',
        ),
        migrations.AlterField(
            model_name='newpipediameter',
            name='option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '--------'), (1, 'А'), (2, 'Б'), (3, 'В')], null=True, verbose_name='Исполнение'),
        ),
    ]
