# Generated by Django 4.2 on 2023-10-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0039_alter_attribute_catalog_and_more'),
        ('catalog', '0015_delete_pipediameter_alter_newpipediameter_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPipeDiameter',
            new_name='PipeDiameter',
        ),
    ]
