# Generated by Django 4.2 on 2023-10-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_populate_coveringtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveringtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
