# Generated by Django 4.2.7 on 2023-12-05 19:58

from django.db import migrations, models


def populate_numeric(apps, scheme_editor):
    CoveringType = apps.get_model('catalog', 'CoveringType')

    types = CoveringType.objects.filter(numeric__isnull=True)

    for ctype in types:
        if ctype.name_ru == 'Без покрытия':
            ctype.numeric = 0
        elif ctype.name_ru == 'Гальваника':
            ctype.numeric = 1
        elif ctype.name_ru == 'Цинк':
            ctype.numeric = 2
        elif ctype.name_ru == 'Эмаль':
            ctype.numeric = 3
        else:
            ctype.numeric = 999

    CoveringType.objects.bulk_update(types, fields=['numeric'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_coveringtype_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveringtype',
            name='numeric',
            field=models.IntegerField(null=True, verbose_name='Числовое значение'),
        ),
        migrations.RunPython(populate_numeric),
        migrations.AlterField(
            model_name='coveringtype',
            name='numeric',
            field=models.IntegerField(verbose_name='Числовое значение'),
        ),
    ]
