# Generated by Django 4.2.7 on 2023-12-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_coveringtype_numeric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveringtype',
            options={'ordering': ('numeric',), 'verbose_name': 'тип покрытия', 'verbose_name_plural': 'типы покрытии'},
        ),
    ]
