# Generated by Django 4.2.7 on 2024-01-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_coveringtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='asme_type',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Тип материала по классификации ASME'),
        ),
        migrations.AddField(
            model_name='material',
            name='asme_uns',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Уникальный номер материала по классификации ASME'),
        ),
        migrations.AddField(
            model_name='material',
            name='astm_spec',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Спецификация по стандарту ASTM'),
        ),
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='material',
            name='lz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='max_exhaust_gas_temp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная температура выхлопных газов'),
        ),
        migrations.AddField(
            model_name='material',
            name='max_temp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная рабочая температура материала'),
        ),
        migrations.AddField(
            model_name='material',
            name='min_temp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная рабочая температура материала'),
        ),
        migrations.AddField(
            model_name='material',
            name='rp0',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предел текучести'),
        ),
        migrations.AddField(
            model_name='material',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стандарт'),
        ),
        migrations.AddField(
            model_name='material',
            name='spring_constant',
            field=models.FloatField(blank=True, null=True, verbose_name='Пружинная постоянная'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('A', 'Аустенитные стали'), ('F', 'Ферритные'), ('N', 'Сплавы на основе никеля')], max_length=1, null=True, blank=True, verbose_name='Тип материала'),
        ),
    ]
