# Generated by Django 4.2.7 on 2024-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_populate_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'покрытие',
                'verbose_name_plural': 'покрытия',
                'ordering': ('name',),
            },
        ),
    ]
