# Generated by Django 4.2.7 on 2024-09-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_covering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveringtype',
            options={'ordering': ('numeric',), 'verbose_name': 'Тип покрытия', 'verbose_name_plural': 'Типы покрытий'},
        ),
    ]
