# Generated by Django 4.2.7 on 2024-12-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_material_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.directory', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Запись в справочнике',
                'verbose_name_plural': 'Записи в справочнике',
            },
        ),
        migrations.CreateModel(
            name='DirectoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('int', 'Целое число'), ('float', 'Число с плавающей точкой'), ('str', 'Строка'), ('bool', 'Логическое значение')], max_length=10, verbose_name='Тип поля')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.directory', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Поле в справочнике',
                'verbose_name_plural': 'Поля в справочнике',
            },
        ),
        migrations.CreateModel(
            name='DirectoryEntryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='Целое число')),
                ('float_value', models.FloatField(blank=True, null=True, verbose_name='Вещественное число')),
                ('str_value', models.CharField(blank=True, null=True, verbose_name='Строка')),
                ('bool_value', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('directory_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.directoryfield', verbose_name='Поле')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.directoryentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Значение поля',
                'verbose_name_plural': 'Значения полей',
            },
        ),
    ]
