# Generated by Django 4.2.7 on 2024-12-25 14:15

from django.db import migrations, models
import pybarker.django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_directory_directoryentry_directoryfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='display_name_template',
            field=models.TextField(blank=True, default='', verbose_name='Шаблон отображения'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отображаемое имя'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='display_name_errors',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, default=list, verbose_name='Ошибки при генерации имени'),
        ),
    ]
