# Generated by Django 5.1.4 on 2025-02-10 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_directory_display_name_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Расстояние между опорами, мм')),
            ],
            options={
                'verbose_name': 'Расстояние между опорами',
                'verbose_name_plural': 'Расстояния между опорами',
                'ordering': ['value'],
            },
        ),
    ]
