# Generated by Django 5.1.4 on 2025-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_supportdistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название семейства')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product_families/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Семейство изделий',
                'verbose_name_plural': 'Семейства изделий',
                'ordering': ['name'],
            },
        ),
    ]
