# Generated by Django 5.1.4 on 2025-02-17 00:28

import django.db.models.deletion
from django.db import migrations, models


def populate_product_class_for_product_family(apps, scheme_editor):
    ProductClass = apps.get_model('catalog', 'ProductClass')
    ProductFamily = apps.get_model('catalog', 'ProductFamily')

    product_families = ProductFamily.objects.filter(product_class__isnull=True)

    if product_families.exists():
        product_class = ProductClass.objects.create(name='Безымянный класс изделия')
        product_families.update(product_class=product_class)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_productfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Класс изделия',
                'verbose_name_plural': 'Классы изделий',
            },
        ),
        migrations.AddField(
            model_name='productfamily',
            name='product_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_families', to='catalog.productclass', verbose_name='Класс изделия'),
        ),
        migrations.RunPython(populate_product_class_for_product_family),
        migrations.AlterField(
            model_name='productfamily',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_families', to='catalog.productclass', verbose_name='Класс изделия'),
        )
    ]
