# Generated by Django 5.1.4 on 2025-02-19 04:50

from django.db import migrations, models


LOAD_GROUP_LGV_LIST = (12, 12, 12, 12, 12, 16, 20, 24, 30, 36, 42, 48, 64, 72, 80, 90)
MAX_SIZE = len(LOAD_GROUP_LGV_LIST)


def load_iterator(model, series_name, rated_stroke_50, rated_stroke_100, rated_stroke_200, design_loads):
    total = len(design_loads)
    loads = []

    for index in range(total):
        size = index + 1
        load_group_lgv = LOAD_GROUP_LGV_LIST[index]
        design_load = design_loads[index]

        loads.append(
            model(
                size=size,
                series_name=series_name,
                rated_stroke_50=rated_stroke_50,
                rated_stroke_100=rated_stroke_100,
                rated_stroke_200=rated_stroke_200,
                load_group_lgv=load_group_lgv,
                design_load=design_load,
            )
        )

    return loads


def stiffness_iterator(model, series_name, rated_stroke, values):
    stiffness_list = []

    for index, value in enumerate(values):
        size = index + 1
        stiffness_list.append(model(size=size, series_name=series_name, rated_stroke=rated_stroke, value=value))

    return stiffness_list


def load_standard_series_loads(model):
    series_name = 'standard_series'

    loads = []
    loads += load_iterator(model, series_name, 0, 0, 0, (
    0.16, 0.32, 0.66, 1.30, 2.30, 3.90, 6.60, 10.9, 16.5, 23.0, 33.0, 43.6, 66.0, 92.0, 132, 165))
    loads += load_iterator(model, series_name, 2.5, 5, 10, (
    0.18, 0.35, 0.73, 1.44, 2.54, 4.31, 7.27, 12.0, 18.2, 25.4, 36.4, 48.0, 72.7, 101, 145, 182))
    loads += load_iterator(model, series_name, 5.0, 10, 20, (
    0.19, 0.39, 0.79, 1.57, 2.77, 4.71, 7.94, 13.1, 19.9, 27.7, 39.7, 52.4, 79.4, 111, 159, 199))
    loads += load_iterator(model, series_name, 7.5, 15, 30, (
    0.21, 0.42, 0.86, 1.71, 3.01, 5.12, 8.61, 14.2, 21.5, 30.1, 43.1, 56.9, 86.1, 120, 172, 215))
    loads += load_iterator(model, series_name, 10.0, 20, 40, (
    0.23, 0.46, 0.93, 1.84, 3.24, 5.52, 9.28, 15.3, 23.2, 32.4, 46.4, 61.3, 92.8, 130, 186, 232))
    loads += load_iterator(model, series_name, 12.5, 25, 50, (
    0.25, 0.49, 1.00, 1.98, 3.48, 5.93, 9.95, 16.4, 24.9, 34.8, 49.8, 65.7, 99.5, 139, 199, 249))
    loads += load_iterator(model, series_name, 15.0, 30, 60,
                           (0.26, 0.52, 1.06, 2.11, 3.71, 6.33, 10.6, 17.5, 26.6, 37.1, 53.1, 70.1, 106, 148, 212, 266))
    loads += load_iterator(model, series_name, 17.5, 35, 70,
                           (0.28, 0.56, 1.13, 2.25, 3.95, 6.74, 11.3, 18.6, 28.2, 39.5, 56.5, 74.5, 113, 158, 226, 282))
    loads += load_iterator(model, series_name, 20.0, 40, 80,
                           (0.30, 0.59, 1.20, 2.38, 4.18, 7.14, 12.0, 19.7, 29.9, 41.8, 59.8, 79.0, 120, 167, 239, 299))
    loads += load_iterator(model, series_name, 22.5, 45, 90,
                           (0.31, 0.63, 1.26, 2.52, 4.42, 7.55, 12.6, 20.8, 31.6, 44.2, 63.2, 83.4, 126, 177, 253, 316))
    loads += load_iterator(model, series_name, 25.0, 50, 100,
                           (0.33, 0.66, 1.33, 2.65, 4.65, 7.95, 13.3, 22.0, 33.3, 46.5, 66.5, 87.8, 133, 186, 266, 333))
    loads += load_iterator(model, series_name, 27.5, 55, 110,
                           (0.35, 0.69, 1.40, 2.79, 4.89, 8.36, 14.0, 23.1, 34.9, 48.9, 69.9, 92.2, 140, 195, 279, 349))
    loads += load_iterator(model, series_name, 30.0, 60, 120,
                           (0.36, 0.73, 1.46, 2.92, 5.12, 8.76, 14.6, 24.2, 36.6, 51.2, 73.2, 96.6, 146, 205, 293, 366))
    loads += load_iterator(model, series_name, 32.5, 65, 130,
                           (0.38, 0.76, 1.53, 3.06, 5.36, 9.17, 15.3, 25.3, 38.3, 53.6, 76.6, 101, 153, 214, 306, 383))
    loads += load_iterator(model, series_name, 35.0, 70, 140,
                           (0.40, 0.80, 1.60, 3.19, 5.59, 9.57, 16.0, 26.4, 40.0, 55.9, 79.9, 105, 160, 224, 320, 400))
    loads += load_iterator(model, series_name, 37.5, 75, 150,
                           (0.42, 0.83, 1.67, 3.33, 5.83, 9.98, 16.7, 27.5, 41.6, 58.3, 83.3, 110, 167, 233, 333, 416))
    loads += load_iterator(model, series_name, 40.0, 80, 160,
                           (0.43, 0.86, 1.73, 3.46, 6.06, 10.4, 17.3, 28.6, 43.3, 60.6, 86.6, 114, 173, 242, 346, 433))
    loads += load_iterator(model, series_name, 42.5, 85, 170,
                           (0.45, 0.90, 1.80, 3.60, 6.30, 10.8, 18.0, 29.7, 45.0, 63.0, 90.0, 119, 180, 252, 360, 450))
    loads += load_iterator(model, series_name, 45.0, 90, 180,
                           (0.47, 0.93, 1.87, 3.73, 6.53, 11.2, 18.7, 30.8, 46.7, 65.3, 93.3, 123, 187, 261, 373, 467))
    loads += load_iterator(model, series_name, 47.5, 95, 190,
                           (0.48, 0.97, 1.93, 3.87, 6.77, 11.6, 19.3, 31.9, 48.3, 67.7, 96.7, 128, 193, 271, 387, 483))
    loads += load_iterator(model, series_name, 50.0, 100, 200,
                           (0.50, 1.00, 2.00, 4.00, 7.00, 12.0, 20.0, 33.0, 50.0, 70.0, 100, 132, 200, 280, 400, 500))

    model.objects.bulk_create(loads)


def load_standard_series_spring_stiffnesses(model):
    series_name = 'standard_series'

    spring_stiffnesses = []
    spring_stiffnesses += stiffness_iterator(model, series_name, 50, (
        6.8, 13.6, 26.8, 54.0, 94.0, 162.0, 268.0, 442.0, 670.0, 940, 1340, 1768, 2680, 3760, 5360, 6700))
    spring_stiffnesses += stiffness_iterator(model, series_name, 100, (
        3.4, 6.8, 13.4, 27.0, 47.0, 81.0, 134.0, 221.0, 335.0, 470, 670, 884, 1340, 1880, 2680, 3350))
    spring_stiffnesses += stiffness_iterator(model, series_name, 200, (
        1.7, 3.4, 6.7, 13.5, 23.5, 40.5, 67, 110.5, 167.5, 235, 335, 442, 670, 940, 1340, 1675))

    model.objects.bulk_create(spring_stiffnesses)


def load_l_series_loads(model):
    series_name = 'l_series'

    loads = []
    loads += load_iterator(model, series_name, 0, 0, 0, (0.04, 0.12, 0.41, 0.83, 1.66, 3.33, 6.7, 13.3, 20, 27, 33, 53, 80, 107, 133, 167))
    loads += load_iterator(model, series_name, 2.5, 5, 10, (0.05, 0.14, 0.45, 0.91, 1.83, 3.66, 7.3, 14.7, 22, 29, 37, 59, 88, 117, 147, 183))
    loads += load_iterator(model, series_name, 5.0, 10, 20, (0.06, 0.16, 0.49, 1.00, 1.99, 4.00, 8.0, 16.0, 24, 32, 40, 64, 96, 128, 160, 200))
    loads += load_iterator(model, series_name, 7.5, 15, 30, (0.07, 0.18, 0.53, 1.08, 2.16, 4.33, 8.7, 17.3, 26, 35, 43, 69, 104, 139, 173, 217))
    loads += load_iterator(model, series_name, 10.0, 20, 40, (0.08, 0.20, 0.58, 1.16, 2.33, 4.66, 9.3, 18.7, 28, 37, 47, 75, 112, 149, 187, 233))
    loads += load_iterator(model, series_name, 12.5, 25, 50, (0.09, 0.22, 0.62, 1.25, 2.49, 5.00, 10.0, 20.0, 30, 40, 50, 80, 120, 160, 200, 250))
    loads += load_iterator(model, series_name, 15.0, 30, 60, (0.10, 0.24, 0.66, 1.33, 2.66, 5.33, 10.7, 21.3, 32, 43, 53, 85, 128, 171, 213, 267))
    loads += load_iterator(model, series_name, 17.5, 35, 70, (0.11, 0.26, 0.70, 1.41, 2.83, 5.66, 11.3, 22.7, 34, 45, 57, 91, 136, 181, 227, 283))
    loads += load_iterator(model, series_name, 20.0, 40, 80, (0.12, 0.28, 0.74, 1.49, 2.99, 5.99, 12.0, 24.0, 36, 48, 60, 96, 144, 192, 240, 300))
    loads += load_iterator(model, series_name, 22.5, 45, 90, (0.13, 0.30, 0.78, 1.58, 3.16, 6.33, 12.7, 25.3, 38, 51, 63, 101, 152, 203, 253, 317))
    loads += load_iterator(model, series_name, 25.0, 50, 100, (0.15, 0.32, 0.83, 1.66, 3.32, 6.66, 13.3, 26.7, 40, 53, 67, 107, 160, 213, 267, 333))
    loads += load_iterator(model, series_name, 27.5, 55, 110, (0.16, 0.35, 0.87, 1.74, 3.49, 6.99, 14.0, 28.0, 42, 56, 70, 112, 168, 224, 280, 350))
    loads += load_iterator(model, series_name, 30.0, 60, 120, (0.17, 0.37, 0.91, 1.83, 3.66, 7.33, 14.7, 29.3, 44, 59, 73, 117, 176, 235, 293, 367))
    loads += load_iterator(model, series_name, 32.5, 65, 130, (0.18, 0.39, 0.95, 1.91, 3.82, 7.66, 15.3, 30.7, 46, 61, 77, 123, 184, 245, 307, 383))
    loads += load_iterator(model, series_name, 35.0, 70, 140, (0.19, 0.41, 0.99, 1.99, 3.99, 7.99, 16.0, 32.0, 48, 64, 80, 128, 192, 256, 320, 400))
    loads += load_iterator(model, series_name, 37.5, 75, 150, (0.20, 0.43, 1.03, 2.08, 4.16, 8.33, 16.7, 33.3, 50, 67, 83, 133, 200, 267, 333, 417))
    loads += load_iterator(model, series_name, 40.0, 80, 160, (0.21, 0.45, 1.07, 2.16, 4.32, 8.66, 17.3, 34.7, 52, 69, 87, 139, 208, 277, 347, 433))
    loads += load_iterator(model, series_name, 42.5, 85, 170, (0.22, 0.47, 1.12, 2.24, 4.49, 8.99, 18.0, 36.0, 54, 72, 90, 144, 216, 288, 360, 450))
    loads += load_iterator(model, series_name, 45.0, 90, 180, (0.23, 0.49, 1.16, 2.32, 4.66, 9.32, 18.7, 37.3, 56, 75, 93, 149, 224, 299, 373, 467))
    loads += load_iterator(model, series_name, 47.5, 95, 190, (0.24, 0.51, 1.20, 2.41, 4.82, 9.66, 19.3, 38.7, 58, 77, 97, 155, 232, 309, 387, 483))
    loads += load_iterator(model, series_name, 50.0, 100, 200, (0.25, 0.52, 1.25, 2.50, 5.00, 10.0, 20.0, 40.0, 60, 80, 100, 160, 240, 320, 400, 500))

    model.objects.bulk_create(loads)


def load_l_series_spring_stiffnesses(model):
    series_name = 'l_series'

    spring_stiffnesses = []
    spring_stiffnesses += stiffness_iterator(model, series_name, 50, ( None, 8.3, 16.6, 33.3, 66.6, 133.3, 266.6, 533.3, 800.0, 1067, 1333, 2133, 3200, 4266, 5333, 6667))
    spring_stiffnesses += stiffness_iterator(model, series_name, 100, ( 2.1, 4.1, 8.3, 16.6, 33.3, 66.6, 133.3, 266.6, 400.0, 533, 667, 1066, 1600, 2133, 2666, 3333))
    spring_stiffnesses += stiffness_iterator(model, series_name, 200, ( None, 2.1, 4.1, 8.3, 16.6, 33.3, 66.6, 133.3, 200, 267, 333, 533, 800, 1066, 1333, 1667))

    model.objects.bulk_create(spring_stiffnesses)


def load_initial_data(apps, schema_editor):
    Load = apps.get_model('catalog', 'Load')
    SpringStiffness = apps.get_model('catalog', 'SpringStiffness')

    load_standard_series_loads(Load)
    load_standard_series_spring_stiffnesses(SpringStiffness)
    load_l_series_loads(Load)
    load_l_series_spring_stiffnesses(SpringStiffness)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_productclass_productfamily_product_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(choices=[('standard_series', 'Standard Series'), ('l_series', 'L Series')], max_length=15, verbose_name='Наименование серии')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
                ('rated_stroke_50', models.PositiveIntegerField(verbose_name='Номинальный ход 50')),
                ('rated_stroke_100', models.PositiveIntegerField(verbose_name='Номинальный ход 100')),
                ('rated_stroke_200', models.PositiveIntegerField(verbose_name='Номинальный ход 200')),
                ('load_group_lgv', models.PositiveIntegerField(verbose_name='Группа LGV')),
                ('design_load', models.FloatField(verbose_name='Расчетная нагрузка')),
            ],
            options={
                'verbose_name': 'Нагрузка',
                'verbose_name_plural': 'Нагрузки',
            },
        ),
        migrations.CreateModel(
            name='SpringStiffness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(choices=[('standard_series', 'Standard Series'), ('l_series', 'L Series')], max_length=15, verbose_name='Наименование серии')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
                ('rated_stroke', models.PositiveIntegerField(verbose_name='Номинальный ход')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Жесткость')),
            ],
            options={
                'verbose_name': 'Пружинная жесткость',
                'verbose_name_plural': 'Пружинные жесткости',
            },
        ),
        migrations.RunPython(load_initial_data),
    ]
