# Generated by Django 5.1.4 on 2025-03-03 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_load_springstiffness'),
        ('ops', '0091_item_chain_weight_item_chain_weight_errors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeMountingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа креплений к трубе',
                'verbose_name_plural': 'Группы креплений к трубе',
            },
        ),
        migrations.AddField(
            model_name='productfamily',
            name='is_upper_mount_selectable',
            field=models.BooleanField(blank=True, default=False, verbose_name='Доступен выбор верхнего крепления'),
        ),
        migrations.CreateModel(
            name='PipeMountingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_spring_blocks', models.PositiveSmallIntegerField(verbose_name='Количество пружинных блоков')),
                ('pipe_direction', models.CharField(choices=[('x', 'X'), ('y', 'Y')], max_length=1, verbose_name='Направление трубы')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productfamily', verbose_name='Семейство изделия')),
                ('variants', models.ManyToManyField(related_name='+', to='ops.variant', verbose_name='Типы креплений')),
            ],
            options={
                'verbose_name': 'Правило выбора крепления к трубе',
                'verbose_name_plural': 'Правила выбора креплений к трубе',
            },
        ),
    ]
