# Generated by Django 5.1.4 on 2025-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_pipemountinggroup_and_more'),
        ('ops', '0094_remove_variant_pipe_mounting_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipemountinggroup',
            name='variants',
            field=models.ManyToManyField(related_name='+', to='ops.variant', verbose_name='Типы креплений'),
        ),
    ]
