# Generated by Django 5.1.4 on 2025-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_pipemountinggroup_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipemountingrule',
            name='variants',
        ),
        migrations.AddField(
            model_name='pipemountingrule',
            name='pipe_mounting_groups',
            field=models.ManyToManyField(blank=True, related_name='+', to='catalog.pipemountinggroup', verbose_name='Группы креплений к трубе'),
        ),
    ]
