# Generated by Django 5.1.4 on 2025-03-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_remove_pipemountingrule_variants_and_more'),
        ('ops', '0096_alter_basecomposition_base_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('studs', 'Список шпилек'), ('coupling', 'Список муфт')], max_length=8, unique=True, verbose_name='Тип группы')),
                ('detail_types', models.ManyToManyField(blank=True, related_name='+', to='ops.detailtype', verbose_name='Типы детали/изделии')),
            ],
            options={
                'verbose_name': 'Группа компонентов',
                'verbose_name_plural': 'Группы компонентов',
            },
        ),
    ]
