# Generated by Django 5.1.4 on 2025-03-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_componentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='has_rod',
            field=models.BooleanField(blank=True, default=False, verbose_name='Присутствует шток'),
        ),
    ]
