# Generated by Django 5.1.4 on 2025-05-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_productfamily_has_rod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipemountingrule',
            name='pipe_direction',
            field=models.CharField(choices=[('x', 'X'), ('y', 'Y'), ('z', 'Z')], max_length=1, verbose_name='Направление трубы'),
        ),
    ]
