# Generated by Django 5.1.4 on 2025-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_pipemountingrule_pipe_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='covering',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='coveringtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='directory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='directoryentryvalue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='directoryfield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='load',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='loadgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='nominaldiameter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='pipediameter',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='pipemountinggroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='pipemountingrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='springstiffness',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='supportdistance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
    ]
