# Generated by Django 5.1.4 on 2025-05-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_componentgroup_deleted_at_covering_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentgroup',
            name='group_type',
            field=models.CharField(choices=[('studs', 'Список шпилек'), ('coupling', 'Список муфт'), ('series_selectable', 'С выбором серии')], max_length=17, unique=True, verbose_name='Тип группы'),
        ),
    ]
