# Generated by Django 5.1.4 on 2025-05-20 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_alter_componentgroup_group_type'),
        ('ops', '0107_variant_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringBlockFamilyBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productfamily', verbose_name='Семейство изделия')),
                ('spring_block_types', models.ManyToManyField(related_name='+', to='ops.detailtype', verbose_name='Допустимые типы пружинных блоков')),
            ],
            options={
                'verbose_name': 'Связь семейства с типами пружинных блоков',
                'verbose_name_plural': 'Связи семейств с типами пружинных блоков',
            },
        ),
    ]
