# Generated by Django 5.1.4 on 2025-06-16 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_springblockfamilybinding"),
        ("ops", "0109_formula_changing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClampSelectionMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail_types",
                    models.ManyToManyField(
                        to="ops.detailtype", verbose_name="Типы деталей/изедлий"
                    ),
                ),
                (
                    "product_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productfamily",
                        verbose_name="Семейство изделии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матрица подбора хомутов",
                "verbose_name_plural": "Матрицы подбора хомутов",
            },
        ),
        migrations.CreateModel(
            name="ClampSelectionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hanger_load_group",
                    models.PositiveIntegerField(
                        verbose_name="Нагрузочная группа подвеса"
                    ),
                ),
                (
                    "clamp_load_group",
                    models.PositiveIntegerField(
                        verbose_name="Нагрузочная группа хомута"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("unlimited", "Собирается без ограничений"),
                            ("adapter_required", "Собирается через переходник"),
                            ("not_possible", "Не собирается"),
                        ],
                        max_length=20,
                        verbose_name="Результат подбора",
                    ),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.clampselectionmatrix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись матрицы подбора",
                "verbose_name_plural": "Записи матрицы подбора",
                "unique_together": {
                    ("matrix", "hanger_load_group", "clamp_load_group")
                },
            },
        ),
    ]
