# Generated by Django 5.1.4 on 2025-06-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_springblockfamilybinding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pipemountingrule",
            options={
                "verbose_name": "Правило выбора крепления",
                "verbose_name_plural": "Правила выбора креплений",
            },
        ),
        migrations.AddField(
            model_name="pipemountingrule",
            name="mounting_groups_b",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="catalog.pipemountinggroup",
                verbose_name="Группы крепления В",
            ),
        ),
        migrations.AlterField(
            model_name="productfamily",
            name="has_rod",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Альтернативный расчет высоты за счет регулировки штока",
            ),
        ),
    ]
