# Generated by Django 5.1.4 on 2025-06-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0042_alter_pipemountingrule_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSBCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fn",
                    models.PositiveIntegerField(
                        verbose_name="Номинальная нагрузка, kH"
                    ),
                ),
                ("stroke", models.PositiveIntegerField(verbose_name="Ход, мм")),
                ("f", models.PositiveIntegerField(verbose_name="F, мм")),
                ("l", models.PositiveIntegerField(blank=True, null=True, verbose_name="L, мм")),
                ("l1", models.PositiveIntegerField(blank=True, null=True, verbose_name="L1, мм")),
                ("l2_min", models.PositiveIntegerField(blank=True, null=True, verbose_name="L2 мин., мм")),
                ("l2_max", models.PositiveIntegerField(blank=True, null=True, verbose_name="L2 макс., мм")),
                ("l3_min", models.PositiveIntegerField(verbose_name="L3 мин., мм")),
                ("l3_max", models.PositiveIntegerField(verbose_name="L3 макс., мм")),
                ("l4", models.PositiveIntegerField(verbose_name="L4, мм")),
                ("a", models.PositiveIntegerField(verbose_name="A")),
                ("b", models.PositiveIntegerField(verbose_name="B")),
                ("h", models.PositiveIntegerField(verbose_name="H")),
                ("diameter_j", models.PositiveIntegerField(verbose_name="ØJ")),
            ],
            options={
                "verbose_name": "Гидроамортизатор SSB",
                "verbose_name_plural": "Гидроамортизаторы SSB",
            },
        ),
    ]
