# Generated by Django 5.1.4 on 2025-07-14 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_clampselectionmatrix_clampselectionentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clampselectionentry",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="catalog.clampselectionmatrix",
                verbose_name="Матрица подбора",
            ),
        ),
    ]
