# Generated by Django 5.1.4 on 2025-06-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0044_populate_ssbcatalog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ssbcatalog",
            options={
                "ordering": ["fn", "stroke", "l"],
                "verbose_name": "Гидроамортизатор SSB",
                "verbose_name_plural": "Гидроамортизаторы SSB",
            },
        ),
    ]
