# Generated by Django 5.1.4 on 2025-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0045_alter_ssbcatalog_options"),
        ("ops", "0110_alter_attribute_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("studs", "Список шпилек"),
                    ("coupling", "Список муфт"),
                    ("series_selectable", "С выбором серии"),
                ],
                max_length=17,
                verbose_name="Тип группы",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("group_type",),
                name="unique_group_type_if_not_deleted",
            ),
        ),
    ]
