# Generated by Django 5.1.4 on 2025-07-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_alter_componentgroup_group_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClampMaterialCoefficient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_group",
                    models.CharField(max_length=32, verbose_name="Группа материала"),
                ),
                (
                    "temperature",
                    models.PositiveSmallIntegerField(verbose_name="Температура, °C"),
                ),
                (
                    "coefficient",
                    models.FloatField(verbose_name="Коэффициент материала"),
                ),
            ],
            options={
                "verbose_name": "Коэффициент материала для хомута",
                "verbose_name_plural": "Коэффициенты материалов для хомутов",
                "ordering": ["material_group", "temperature"],
            },
        ),
    ]
