# Generated by Django 5.1.4 on 2025-07-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0048_populate_clampmaterialcoefficient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clampmaterialcoefficient",
            options={
                "ordering": ["material_group", "temperature_from"],
                "verbose_name": "Коэффициент материала для хомута",
                "verbose_name_plural": "Коэффициенты материалов для хомутов",
            },
        ),
        migrations.RenameField(
            model_name="clampmaterialcoefficient",
            old_name="temperature",
            new_name="temperature_from",
        ),
    ]
