# Generated by Django 5.1.4 on 2025-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0049_alter_clampmaterialcoefficient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clampmaterialcoefficient",
            options={
                "ordering": ["material_group", "temperature_from", "temperature_to"],
                "verbose_name": "Коэффициент материала для хомута",
                "verbose_name_plural": "Коэффициенты материалов для хомутов",
            },
        ),
        migrations.AddField(
            model_name="clampmaterialcoefficient",
            name="temperature_to",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Температура до, °C"
            ),
        ),
        migrations.AlterField(
            model_name="clampmaterialcoefficient",
            name="temperature_from",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Температура от, °C"
            ),
        ),
    ]
