# Generated by Django 5.1.4 on 2025-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0051_repopulate_clampmaterialcoefficient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clampmaterialcoefficient",
            options={
                "ordering": [
                    "material_group",
                    models.OrderBy(models.F("temperature_from"), nulls_first=True),
                    "temperature_to",
                ],
                "verbose_name": "Коэффициент материала для хомута",
                "verbose_name_plural": "Коэффициенты материалов для хомутов",
            },
        ),
    ]
