# Generated by Django 5.1.4 on 2025-07-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0052_alter_clampmaterialcoefficient_options"),
        ("ops", "0113_alter_item_inner_id_item_unique_inner_id_not_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipemountinggroup",
            name="variants",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="ops.variant",
                verbose_name="Типы креплений",
            ),
        ),
    ]
