# Generated by Django 5.1.4 on 2025-07-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_alter_clampselectionentry_matrix"),
        ("catalog", "0053_alter_pipemountinggroup_variants"),
    ]

    operations = []
