# Generated by Django 5.1.4 on 2025-07-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_alter_pipemountinggroup_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSGCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.PositiveIntegerField(verbose_name='Номинальная нагрузка, kN')),
                ('l_min', models.PositiveIntegerField(verbose_name='L мин., мм')),
                ('l_max', models.PositiveIntegerField(verbose_name='L макс., мм')),
                ('l1', models.PositiveIntegerField(blank=True, null=True, verbose_name='L1, мм')),
                ('d', models.PositiveIntegerField(blank=True, null=True, verbose_name='ØD')),
                ('d1', models.PositiveIntegerField(blank=True, null=True, verbose_name='ØD1')),
                ('r', models.PositiveIntegerField(blank=True, null=True, verbose_name='R')),
                ('s', models.PositiveIntegerField(blank=True, null=True, verbose_name='S')),
                ('sw', models.PositiveIntegerField(blank=True, null=True, verbose_name='SW')),
                ('regulation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Регулировка, мм')),
            ],
            options={
                'verbose_name': 'Распорка SSG',
                'verbose_name_plural': 'Распорки SSG',
                'ordering': ['fn', 'l_min'],
            },
        ),
    ]
