# Generated by Django 5.1.4 on 2025-07-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0054_merge_20250714_0836"),
        ("catalog", "0055_populate_ssgcatalog"),
    ]

    operations = []
