# Generated by Django 5.1.4 on 2025-07-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0057_clampselectionentry_additional_clamp_load_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clampselectionmatrix",
            name="product_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.productfamily",
                verbose_name="Семейство изделии",
            ),
        ),
    ]
