# Generated by Django 5.1.4 on 2025-07-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_add_remaining_ssg_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssgcatalog',
            options={'ordering': ['type', 'l_min'], 'verbose_name': 'Распорка SSG (каталог)', 'verbose_name_plural': 'Распорки SSG (каталог)'},
        ),
        migrations.AddField(
            model_name='ssgcatalog',
            name='delta_l',
            field=models.FloatField(blank=True, null=True, verbose_name='ΔL, кг/м'),
        ),
        migrations.AddField(
            model_name='ssgcatalog',
            name='fixed_part',
            field=models.FloatField(blank=True, null=True, verbose_name='Фиксированная часть, кг'),
        ),
        migrations.AddField(
            model_name='ssgcatalog',
            name='h',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Толщина H, мм'),
        ),
        migrations.AddField(
            model_name='ssgcatalog',
            name='l2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер L2, мм'),
        ),
        migrations.AddField(
            model_name='ssgcatalog',
            name='sw1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер SW1 (под ключ), мм'),
        ),
        migrations.AddField(
            model_name='ssgcatalog',
            name='sw2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер SW2 (под ключ), мм'),
        ),
        migrations.AddField(
            model_name='ssgcatalog',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Тип 1'), (2, 'Тип 2')], null=True, verbose_name='Тип распорки'),
        ),
        migrations.AlterField(
            model_name='clampselectionmatrix',
            name='product_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productfamily', verbose_name='Семейство изделий'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр D, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='d1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр D1, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='fn',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номинальная нагрузка, кН'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='l1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер L1, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='l_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. длина L, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='l_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мин. длина L, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='r',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='R (радиус/гиб), мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='regulation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Регулировка длины, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='s',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Толщина S, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='sw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер SW (под ключ), мм'),
        ),
        migrations.AddConstraint(
            model_name='ssgcatalog',
            constraint=models.UniqueConstraint(fields=('fn', 'type', 'l_min', 'l_max'), name='unique_ssg_variant'),
        ),
    ]
