# Generated by Django 5.1.4 on 2025-07-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0060_add_remaining_ssg_data"),
        ("ops", "0116_alter_attribute_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="clampselectionmatrix",
            name="clamp_detail_types",
            field=models.ManyToManyField(
                related_name="+", to="ops.detailtype", verbose_name="Хомуты"
            ),
        ),
        migrations.AlterField(
            model_name="clampselectionmatrix",
            name="detail_types",
            field=models.ManyToManyField(
                related_name="+",
                to="ops.detailtype",
                verbose_name="Типы деталей/изделии",
            ),
        ),
        migrations.AlterField(
            model_name="clampselectionmatrix",
            name="product_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.productfamily",
                verbose_name="Семейство изделий",
            ),
        ),
    ]
