# Generated by Django 5.1.4 on 2025-07-22 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_add_remaining_ssg_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clampselectionmatrix',
            name='product_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productfamily', verbose_name='Семейство изделий'),
        ),
    ]
