# Generated by Django 5.1.4 on 2025-07-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0061_clampselectionmatrix_clamp_detail_types_and_more"),
        ("catalog", "0062_refactor_ssg_catalog"),
    ]

    operations = []
