# Generated by Django 5.1.4 on 2025-07-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0063_merge_20250728_1731"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clampselectionentry",
            options={
                "ordering": ["matrix", "hanger_load_group", "clamp_load_group"],
                "verbose_name": "Запись матрицы подбора",
                "verbose_name_plural": "Записи матрицы подбора",
            },
        ),
        migrations.RemoveField(
            model_name="clampselectionentry",
            name="additional_clamp_load_group",
        ),
    ]
