# Generated by Django 5.1.4 on 2025-07-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0064_alter_clampselectionentry_options_and_more"),
        ("ops", "0116_alter_attribute_usage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clampselectionentry",
            options={
                "ordering": ["matrix", "hanger_load_group", "clamp_load_group"],
                "verbose_name": "Запись таблицы собираемости",
                "verbose_name_plural": "Записи таблицы собираемости",
            },
        ),
        migrations.AlterModelOptions(
            name="clampselectionmatrix",
            options={
                "verbose_name": "Таблица собираемости для хомутов",
                "verbose_name_plural": "Таблицы собираемости для хомутов",
            },
        ),
        migrations.RemoveField(
            model_name="clampselectionmatrix",
            name="detail_types",
        ),
        migrations.AddField(
            model_name="clampselectionmatrix",
            name="fastener_detail_types",
            field=models.ManyToManyField(
                related_name="+",
                to="ops.detailtype",
                verbose_name="Типы деталей/изделий крепежа",
            ),
        ),
        migrations.AlterField(
            model_name="clampselectionentry",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="catalog.clampselectionmatrix",
                verbose_name="Таблица собираемости",
            ),
        ),
        migrations.AlterField(
            model_name="clampselectionentry",
            name="result",
            field=models.CharField(
                choices=[
                    ("unlimited", "Собирается без ограничений"),
                    ("adapter_required", "Собирается через переходник"),
                    ("not_possible", "Не собирается"),
                ],
                max_length=16,
                verbose_name="Результат подбора",
            ),
        ),
        migrations.AlterField(
            model_name="clampselectionmatrix",
            name="clamp_detail_types",
            field=models.ManyToManyField(
                related_name="+",
                to="ops.detailtype",
                verbose_name="Тип деталей/изделий хомутов",
            ),
        ),
    ]
