# Generated by Django 5.1.4 on 2025-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_alter_clampselectionentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssgcatalog',
            options={'ordering': ['type', 'fn'], 'verbose_name': 'Распорка SSG (каталог)', 'verbose_name_plural': 'Распорки SSG (каталог)'},
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='d',
            field=models.FloatField(blank=True, null=True, verbose_name='Диаметр D, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='d1',
            field=models.FloatField(blank=True, null=True, verbose_name='Диаметр D1, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='h',
            field=models.FloatField(blank=True, null=True, verbose_name='Толщина H, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер L1, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер L2, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='r',
            field=models.FloatField(blank=True, null=True, verbose_name='R (радиус/гиб), мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='regulation',
            field=models.FloatField(blank=True, null=True, verbose_name='Регулировка длины, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='s',
            field=models.FloatField(blank=True, null=True, verbose_name='Толщина S, мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='sw',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер SW (под ключ), мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='sw1',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер SW1 (под ключ), мм'),
        ),
        migrations.AlterField(
            model_name='ssgcatalog',
            name='sw2',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер SW2 (под ключ), мм'),
        ),
    ]
