# Generated by Django 5.1.4 on 2025-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0065_alter_clampselectionentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ssgcatalog",
            options={
                "ordering": ["type", "fn"],
                "verbose_name": "Распорка SSG (каталог)",
                "verbose_name_plural": "Распорки SSG (каталог)",
            },
        ),
        migrations.AddField(
            model_name="productfamily",
            name="selection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_selection", "Подбор переменок"),
                    ("ssg_selection", "Подбор распорок"),
                    ("shock_selection", "Подбор гидроамортизаторов"),
                ],
                max_length=17,
                null=True,
                verbose_name="Тип подбора",
            ),
        ),
    ]
