# Generated by Django 5.1.4 on 2025-08-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0067_overwritten_ssg_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("studs", "Список шпилек"),
                    ("coupling", "Список муфт"),
                    ("fastener", "Список крепежа"),
                    ("series_selectable", "С выбором серии"),
                ],
                max_length=17,
                verbose_name="Тип группы",
            ),
        ),
    ]
