# Generated by Django 5.1.4 on 2025-08-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0068_alter_componentgroup_group_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clampselectionmatrix",
            name="product_family",
        ),
        migrations.AddField(
            model_name="clampselectionmatrix",
            name="product_families",
            field=models.ManyToManyField(
                related_name="+",
                to="catalog.productfamily",
                verbose_name="Семейства изделий",
            ),
        ),
    ]
