# Generated by Django 5.1.4 on 2025-08-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0069_remove_clampselectionmatrix_product_family_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clampselectionentry",
            options={
                "default_permissions": (),
                "ordering": ["matrix", "hanger_load_group", "clamp_load_group"],
                "permissions": (
                    (
                        "add_clampselectionentry",
                        "Может добавлять записи в справочник таблицы собираемости",
                    ),
                    (
                        "change_clampselectionentry",
                        "Может изменять записи в справочник таблицы собираемости",
                    ),
                    (
                        "delete_clampselectionentry",
                        "Может удалять записи в справочник таблицы собираемости",
                    ),
                    (
                        "view_clampselectionentry",
                        "Может просматривать записи в справочник таблицы собираемости",
                    ),
                ),
                "verbose_name": "Запись таблицы собираемости",
                "verbose_name_plural": "Записи таблицы собираемости",
            },
        ),
    ]
