# Generated by Django 5.1.4 on 2025-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0071_rename_clampselectionentry_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clampmaterialcoefficient",
            options={
                "default_permissions": (),
                "ordering": [
                    "material_group",
                    models.OrderBy(models.F("temperature_from"), nulls_first=True),
                    "temperature_to",
                ],
                "permissions": (
                    (
                        "add_clampmaterialcoefficient",
                        "Может добавлять записи в справочник коэффициентов материалов для хомутов",
                    ),
                    (
                        "change_clampmaterialcoefficient",
                        "Может изменять записи в справочник коэффициентов материалов для хомутов",
                    ),
                    (
                        "delete_clampmaterialcoefficient",
                        "Может удалять записи в справочник коэффициентов материалов для хомутов",
                    ),
                    (
                        "view_clampmaterialcoefficient",
                        "Может просматривать записи в справочник коэффициентов материалов для хомутов",
                    ),
                ),
                "verbose_name": "Коэффициент материала для хомута",
                "verbose_name_plural": "Коэффициенты материалов для хомутов",
            },
        ),
        migrations.AlterModelOptions(
            name="componentgroup",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_componentgroup",
                        "Может добавлять записи в справочник групп компонентов",
                    ),
                    (
                        "change_componentgroup",
                        "Может изменять записи в справочник групп компонентов",
                    ),
                    (
                        "delete_componentgroup",
                        "Может удалять записи в справочник групп компонентов",
                    ),
                    (
                        "view_componentgroup",
                        "Может просматривать записи в справочник групп компонентов",
                    ),
                ),
                "verbose_name": "Группа компонентов",
                "verbose_name_plural": "Группы компонентов",
            },
        ),
        migrations.AlterModelOptions(
            name="covering",
            options={
                "default_permissions": (),
                "ordering": ("name",),
                "permissions": (
                    ("add_covering", "Может добавлять запись в справочник покрытий"),
                    ("change_covering", "Может изменять запись в справочник покрытий"),
                    ("delete_covering", "Может удалять запись в справочник покрытий"),
                    (
                        "view_covering",
                        "Может просматривать записи в справочник покрытий",
                    ),
                ),
                "verbose_name": "Покрытие",
                "verbose_name_plural": "Покрытия",
            },
        ),
        migrations.AlterModelOptions(
            name="coveringtype",
            options={
                "default_permissions": (),
                "ordering": ("numeric",),
                "permissions": (
                    (
                        "add_coveringtype",
                        "Может добавлять запись в справочник типов покрытий",
                    ),
                    (
                        "change_coveringtype",
                        "Может изменять запись в справочник типов покрытий",
                    ),
                    (
                        "delete_coveringtype",
                        "Может удалять запись в справочник типов покрытий",
                    ),
                    (
                        "view_coveringtype",
                        "Может просматривать записи в справочник типов покрытий",
                    ),
                ),
                "verbose_name": "Тип покрытия",
                "verbose_name_plural": "Типы покрытий",
            },
        ),
        migrations.AlterModelOptions(
            name="directory",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_directory", "Может создавать кастомные справочники"),
                    ("change_directory", "Может изменять кастомные справочники"),
                    ("delete_directory", "Может удалять кастомные справочники"),
                    ("view_directory", "Может просматривать кастомные справочники"),
                ),
                "verbose_name": "Кастомный справочник",
                "verbose_name_plural": "Кастомные справочники",
            },
        ),
        migrations.AlterModelOptions(
            name="directoryentry",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_directoryentry",
                        "Может добавлять записи в кастомный справочник",
                    ),
                    (
                        "change_directoryentry",
                        "Может изменять записи в кастомном справочнике",
                    ),
                    (
                        "delete_directoryentry",
                        "Может удалять записи в кастомном справочнике",
                    ),
                    (
                        "view_directoryentry",
                        "Может просматривать записи в кастомном справочнике",
                    ),
                ),
                "verbose_name": "Запись в кастомном справочнике",
                "verbose_name_plural": "Записи в кастомном справочнике",
            },
        ),
        migrations.AlterModelOptions(
            name="directoryentryvalue",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_directoryentryvalue",
                        "Может добавлять значения полей в записи кастомного справочника",
                    ),
                    (
                        "change_directoryentryvalue",
                        "Может изменять значения полей в записи кастомного справочника",
                    ),
                    (
                        "delete_directoryentryvalue",
                        "Может удалять значения полей в записи кастомного справочника",
                    ),
                    (
                        "view_directoryentryvalue",
                        "Может просматривать значения полей в записи кастомного справочника",
                    ),
                ),
                "verbose_name": "Значение поля в записи кастомного справочника",
                "verbose_name_plural": "Значения полей в записях кастомного справочника",
            },
        ),
        migrations.AlterModelOptions(
            name="directoryfield",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_directoryfield",
                        "Может добавлять поля в кастомный справочник",
                    ),
                    (
                        "change_directoryfield",
                        "Может изменять поля в кастомном справочнике",
                    ),
                    (
                        "delete_directoryfield",
                        "Может удалять поля в кастомном справочнике",
                    ),
                    (
                        "view_directoryfield",
                        "Может просматривать поля в кастомном справочнике",
                    ),
                ),
                "verbose_name": "Поле в кастомном справочнике",
                "verbose_name_plural": "Поля в кастомном справочнике",
            },
        ),
        migrations.AlterModelOptions(
            name="load",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_load", "Может добавлять записи в справочник нагрузок"),
                    ("change_load", "Может изменять записи в справочник нагрузок"),
                    ("delete_load", "Может удалять записи в справочник нагрузок"),
                    ("view_load", "Может просматривать записи в справочник нагрузок"),
                ),
                "verbose_name": "Нагрузка",
                "verbose_name_plural": "Нагрузки",
            },
        ),
        migrations.AlterModelOptions(
            name="loadgroup",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_loadgroup",
                        "Может добавлять записи в справочник нагрузочных групп",
                    ),
                    (
                        "change_loadgroup",
                        "Может изменять записи в справочник нагрузочных групп",
                    ),
                    (
                        "delete_loadgroup",
                        "Может удалять записи в справочник нагрузочных групп",
                    ),
                    (
                        "view_loadgroup",
                        "Может просматривать записи в справочник нагрузочных групп",
                    ),
                ),
                "verbose_name": "Нагрузочная группа",
                "verbose_name_plural": "Нагрузочные группы",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_material", "Может добавлять записи в справочник материалов"),
                    (
                        "change_material",
                        "Может изменять записи в справочник материалов",
                    ),
                    ("delete_material", "Может удалять записи в справочник материалов"),
                    (
                        "view_material",
                        "Может просматривать записи в справочник материалов",
                    ),
                ),
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
        migrations.AlterModelOptions(
            name="nominaldiameter",
            options={
                "default_permissions": (),
                "ordering": ["dn"],
                "permissions": (
                    (
                        "add_nominaldiameter",
                        "Может добавлять записи в справочник номинальных диаметров",
                    ),
                    (
                        "change_nominaldiameter",
                        "Может изменять записи в справочник номинальных диаметров",
                    ),
                    (
                        "delete_nominaldiameter",
                        "Может удалять записи в справочник номинальных диаметров",
                    ),
                    (
                        "view_nominaldiameter",
                        "Может просматривать записи в справочник номинальных диаметров",
                    ),
                ),
                "verbose_name": "Номинальный диаметр",
                "verbose_name_plural": "Номинальные диаметры",
            },
        ),
        migrations.AlterModelOptions(
            name="pipediameter",
            options={
                "default_permissions": (),
                "ordering": ["standard", "dn"],
                "permissions": (
                    (
                        "add_pipediameter",
                        "Может добавлять записи в справочник номинальных диаметров труб",
                    ),
                    (
                        "change_pipediameter",
                        "Может изменять записи в справочник номинальных диаметров труб",
                    ),
                    (
                        "delete_pipediameter",
                        "Может удалять записи в справочник номинальных диаметров труб",
                    ),
                    (
                        "view_pipediameter",
                        "Может просматривать записи в справочник номинальных диаметров труб",
                    ),
                ),
                "verbose_name": "Номинальный диаметр трубы",
                "verbose_name_plural": "Номинальные диаметры труб",
            },
        ),
        migrations.AlterModelOptions(
            name="pipemountinggroup",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_pipemountinggroup",
                        "Может добавлять записи в справочник групп креплений к трубе",
                    ),
                    (
                        "change_pipemountinggroup",
                        "Может изменять записи в справочник групп креплений к трубе",
                    ),
                    (
                        "delete_pipemountinggroup",
                        "Может удалять записи в справочник групп креплений к трубе",
                    ),
                    (
                        "view_pipemountinggroup",
                        "Может просматривать записи в справочник групп креплений к трубе",
                    ),
                ),
                "verbose_name": "Группа креплений к трубе",
                "verbose_name_plural": "Группы креплений к трубе",
            },
        ),
        migrations.AlterModelOptions(
            name="pipemountingrule",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_pipemountingrule",
                        "Может добавлять записи в справочник правил выбора креплений",
                    ),
                    (
                        "change_pipemountingrule",
                        "Может изменять записи в справочник правил выбора креплений",
                    ),
                    (
                        "delete_pipemountingrule",
                        "Может удалять записи в справочник правил выбора креплений",
                    ),
                    (
                        "view_pipemountingrule",
                        "Может просматривать записи в справочник правил выбора креплений",
                    ),
                ),
                "verbose_name": "Правило выбора крепления",
                "verbose_name_plural": "Правила выбора креплений",
            },
        ),
        migrations.AlterModelOptions(
            name="productclass",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_productclass",
                        "Может добавлять записи в справочник классов изделий",
                    ),
                    (
                        "change_productclass",
                        "Может изменять записи в справочник классов изделий",
                    ),
                    (
                        "delete_productclass",
                        "Может удалять записи в справочник классов изделий",
                    ),
                    (
                        "view_productclass",
                        "Может просматривать записи в справочник классов изделий",
                    ),
                ),
                "verbose_name": "Класс изделия",
                "verbose_name_plural": "Классы изделий",
            },
        ),
        migrations.AlterModelOptions(
            name="productfamily",
            options={
                "default_permissions": (),
                "ordering": ["name"],
                "permissions": (
                    (
                        "add_productfamily",
                        "Может добавлять записи в справочник семейств изделий",
                    ),
                    (
                        "change_productfamily",
                        "Может изменять записи в справочник семейств изделий",
                    ),
                    (
                        "delete_productfamily",
                        "Может удалять записи в справочник семейств изделий",
                    ),
                    (
                        "view_productfamily",
                        "Может просматривать записи в справочник семейств изделий",
                    ),
                ),
                "verbose_name": "Семейство изделий",
                "verbose_name_plural": "Семейства изделий",
            },
        ),
        migrations.AlterModelOptions(
            name="springblockfamilybinding",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_springblockfamilybinding",
                        "Может добавлять запись в справочник связей семейств с типами пружинных блоков",
                    ),
                    (
                        "change_springblockfamilybinding",
                        "Может изменять запись в справочник связей семейств с типами пружинных блоков",
                    ),
                    (
                        "delete_springblockfamilybinding",
                        "Может удалять запись в справочник связей семейств с типами пружинных блоков",
                    ),
                    (
                        "view_springblockfamilybinding",
                        "Может просматривать записи в справочник связей семейств с типами пружинных блоков",
                    ),
                ),
                "verbose_name": "Связь семейства с типами пружинных блоков",
                "verbose_name_plural": "Связи семейств с типами пружинных блоков",
            },
        ),
        migrations.AlterModelOptions(
            name="springstiffness",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "add_springstiffness",
                        "Может добавлять записи в справочник пружинных жесткостей",
                    ),
                    (
                        "change_springstiffness",
                        "Может изменять записи в справочник пружинных жесткостей",
                    ),
                    (
                        "delete_springstiffness",
                        "Может удалять записи в справочник пружинных жесткостей",
                    ),
                    (
                        "view_springstiffness",
                        "Может просматривать записи в справочник пружинных жесткостей",
                    ),
                ),
                "verbose_name": "Пружинная жесткость",
                "verbose_name_plural": "Пружинные жесткости",
            },
        ),
        migrations.AlterModelOptions(
            name="ssbcatalog",
            options={
                "default_permissions": (),
                "ordering": ["fn", "stroke", "l"],
                "permissions": (
                    (
                        "add_ssbcatalog",
                        "Может добавлять записи в каталог гидроамортизаторов SSB",
                    ),
                    (
                        "change_ssbcatalog",
                        "Может изменять записи в каталог гидроамортизаторов SSB",
                    ),
                    (
                        "delete_ssbcatalog",
                        "Может удалять записи в каталог гидроамортизаторов SSB",
                    ),
                    (
                        "view_ssbcatalog",
                        "Может просматривать записи в каталог гидроамортизаторов SSB",
                    ),
                ),
                "verbose_name": "Гидроамортизатор SSB",
                "verbose_name_plural": "Гидроамортизаторы SSB",
            },
        ),
        migrations.AlterModelOptions(
            name="ssgcatalog",
            options={
                "default_permissions": (),
                "ordering": ["type", "fn"],
                "permissions": (
                    ("add_ssgcatalog", "Может добавлять записи в каталог распорок SSG"),
                    (
                        "change_ssgcatalog",
                        "Может изменять записи в каталог распорок SSG",
                    ),
                    (
                        "delete_ssgcatalog",
                        "Может удалять записи в каталог распорок SSG",
                    ),
                    (
                        "view_ssgcatalog",
                        "Может просматривать записи в каталог распорок SSG",
                    ),
                ),
                "verbose_name": "Распорка SSG (каталог)",
                "verbose_name_plural": "Распорки SSG (каталог)",
            },
        ),
        migrations.AlterModelOptions(
            name="supportdistance",
            options={
                "default_permissions": (),
                "ordering": ["value"],
                "permissions": (
                    (
                        "add_supportdistance",
                        "Может добавлять записи в справочник расстояний между опорами",
                    ),
                    (
                        "change_supportdistance",
                        "Может изменять записи в справочник расстояний между опорами",
                    ),
                    (
                        "delete_supportdistance",
                        "Может удалять записи в справочник расстояний между опорами",
                    ),
                    (
                        "view_supportdistance",
                        "Может просматривать записи в справочник расстояний между опорами",
                    ),
                ),
                "verbose_name": "Расстояние между опорами",
                "verbose_name_plural": "Расстояния между опорами",
            },
        ),
    ]
