# Generated by Django 5.1.4 on 2025-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0072_alter_clampmaterialcoefficient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipemountinggroup",
            name="show_variants",
            field=models.BooleanField(
                default=False, verbose_name="Показывать исполнения вместо деталей"
            ),
        ),
    ]
