# Generated by Django 5.1.4 on 2025-09-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0066_alter_ssgcatalog_options_and_more"),
        ("catalog", "0073_pipemountinggroup_show_variants"),
    ]

    operations = []
