# Generated by Django 5.1.4 on 2025-09-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_merge_20250908_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfamily',
            name='selection_type',
            field=models.CharField(blank=True, choices=[('product_selection', 'Подбор переменок'), ('ssg_selection', 'Подбор распорок'), ('shock_selection', 'Подбор гидроамортизаторов'), ('wvd_selection', 'Подбор демпферов')], max_length=17, null=True, verbose_name='Тип подбора'),
        ),
    ]
