# Generated by Django 5.1.4 on 2025-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_alter_ssgcatalog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssgcatalog',
            options={'default_permissions': (), 'ordering': ['type', 'fn'], 'permissions': (('add_ssgcatalog', 'Может добавлять записи в каталог распорок SSG'), ('change_ssgcatalog', 'Может изменять записи в каталог распорок SSG'), ('delete_ssgcatalog', 'Может удалять записи в каталог распорок SSG'), ('view_ssgcatalog', 'Может просматривать записи в каталог распорок SSG')), 'verbose_name': 'Распорка SSG (каталог)', 'verbose_name_plural': 'Распорки SSG (каталог)'},
        ),
        migrations.AlterField(
            model_name='componentgroup',
            name='group_type',
            field=models.CharField(choices=[('studs', 'Список шпилек'), ('coupling', 'Список муфт'), ('fastener', 'Список крепежа'), ('shock_extenders', 'Список удлинителей для амортизаторов'), ('series_selectable', 'С выбором серии')], max_length=17, verbose_name='Тип группы'),
        ),
    ]
