# Generated by Django 5.1.4 on 2025-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0076_alter_ssgcatalog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipemountingrule",
            name="mounting_groups_b",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="catalog.pipemountinggroup",
                verbose_name="Крепление к металлоконструкции (верхнее)",
            ),
        ),
        migrations.AlterField(
            model_name="pipemountingrule",
            name="pipe_mounting_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="catalog.pipemountinggroup",
                verbose_name="Крепление к трубе (нижнее)",
            ),
        ),
    ]
