# Generated by Django 5.1.4 on 2025-09-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0077_alter_pipemountingrule_mounting_groups_b_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pipemountingrule",
            old_name="pipe_mounting_groups",
            new_name="pipe_mounting_groups_bottom",
        ),
        migrations.RenameField(
            model_name="pipemountingrule",
            old_name="mounting_groups_b",
            new_name="pipe_mounting_groups_top",
        ),
    ]
