# Generated by Django 4.2 on 2023-08-08 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.CharField(max_length=255, verbose_name='Номер проекта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('deleted', 'Корзина')], default='draft', max_length=255, verbose_name='Статус')),
                ('load_unit', models.CharField(choices=[('kN', 'kN')], max_length=255, verbose_name='Единица измерения: Нагрузка')),
                ('move_unit', models.CharField(choices=[('mm', 'mm')], max_length=255, verbose_name='Единица измерения: Перемещение')),
                ('temperature_unit', models.CharField(choices=[('C', 'C'), ('F', 'F')], max_length=255, verbose_name='Единица измерения: Температура')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
