# Generated by Django 4.2 on 2023-08-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('add_own_project', 'Может создавать свои проекты'), ('change_own_project', 'Может изменить свои проекты'), ('delete_own_project', 'Может удалить свои проекты'), ('view_own_project', 'Может видеть свои проекты')), 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
    ]
