# Generated by Django 4.2 on 2023-08-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('designation', models.CharField(max_length=32, verbose_name='Обозначение')),
                ('category', models.CharField(choices=[('detail', 'Деталь'), ('assembly_unit', 'Сборочная единица'), ('product', 'Изделие'), ('billet', 'Заготовка')], max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'тип детали/изделия',
                'verbose_name_plural': 'типы деталей/изделии',
            },
        ),
    ]
