# Generated by Django 4.2 on 2023-08-15 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0003_detailtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('inner_id', models.BigIntegerField(blank=True, help_text='Устанавливается автоматически если пустой', null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Внутренний идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('marking', models.CharField(max_length=32, verbose_name='Маркировка')),
                ('load_group', models.CharField(max_length=255, verbose_name='Нагрузочная группа')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('children', models.ManyToManyField(blank=True, related_name='+', to='ops.item', verbose_name='Состав изделия')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'изделие/деталь/сборочная единица',
                'verbose_name_plural': 'изделия/детали/сборочные единицы',
            },
        ),
    ]
