# Generated by Django 4.2 on 2023-08-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('add_own_item', 'Может создавать свои изделия/детали/сборочные единицы'), ('change_own_item', 'Может изменить свои изделия/детали/сборочные единицы'), ('delete_own_item', 'Может удалить свои изделия/детали/сборочные единицы'), ('view_own_item', 'Может видеть свои изделия/детали/сборочные единицы')), 'verbose_name': 'изделие/деталь/сборочная единица', 'verbose_name_plural': 'изделия/детали/сборочные единицы'},
        ),
    ]
