# Generated by Django 4.2 on 2023-08-22 23:00

from django.db import migrations, models
import django.db.models.deletion


def populate_item_materials(apps, scheme_editor):
    Item = apps.get_model('ops', 'Item')
    Material = apps.get_model('catalog', 'Material')

    items = Item.objects.filter(material__isnull=True)

    if items.exists():
        temp_material = Material.objects.create(name='Безымянный материал')
        items.update(material=temp_material)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_populate_materials'),
        ('ops', '0006_alter_item_load_group_detailparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.material', verbose_name='Материал'),
        ),
        migrations.RunPython(populate_item_materials),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.material', verbose_name='Материал'),
        ),
    ]
