# Generated by Django 4.2 on 2023-08-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_populate_materials'),
        ('ops', '0007_alter_item_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('add_own_item', 'Может создавать свои изделия/детали/сборочные единицы'), ('change_own_item', 'Может изменить свои изделия/детали/сборочные единицы'), ('delete_own_item', 'Может удалить свои изделия/детали/сборочные единицы'), ('view_own_item', 'Может видеть свои изделия/детали/сборочные единицы')), 'verbose_name': 'Изделие/Деталь/Сборочная единица', 'verbose_name_plural': 'Изделия/Детали/Сборочные единицы'},
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.material', verbose_name='Материал'),
        ),
    ]
