# Generated by Django 4.2 on 2023-08-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_alter_item_options_alter_item_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailparameters',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detail_parameters', to='ops.item', verbose_name='Деталь'),
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_marking', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маркировка заказчика')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.item', verbose_name='Изделие/Деталь')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ops.project', verbose_name='Проект')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.item', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'табличная часть проекта',
                'verbose_name_plural': 'табличная часть проекта',
            },
        ),
    ]
