# Generated by Django 4.2 on 2023-08-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_alter_detailparameters_item_projectitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectitem',
            old_name='item',
            new_name='original_item',
        ),
    ]
