# Generated by Django 4.2 on 2023-08-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_alter_projectitem_original_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_revision',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ревизионный объект'),
        ),
    ]
