# Generated by Django 4.2 on 2023-08-27 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_item_is_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='revision',
        ),
        migrations.AlterField(
            model_name='item',
            name='inner_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Внутренний идентификатор'),
        ),
        migrations.CreateModel(
            name='ProjectItemRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='ops.projectitem', verbose_name='Элемент табличной части')),
                ('revision_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.item', verbose_name='Ревизионный объект')),
            ],
            options={
                'verbose_name': 'ревизия объекта',
                'verbose_name_plural': 'ревизии объекта',
            },
        ),
    ]
