# Generated by Django 4.2 on 2023-09-18 10:23

from django.db import migrations, models


def delete_double(apps, schema_editor):
    DetailType = apps.get_model('ops', 'DetailType')
    designation_list = []
    for item in DetailType.objects.all():
        if item.designation not in designation_list:
            designation_list.append(item.designation)
        else:
            print(f'Удаляю: {item.designation} ({item.id})')
            item.delete()
    print('Success!')


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_populate_detail_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='short',
            field=models.IntegerField(choices=[(1, 'Полухомут'), (2, 'Основание'), (3, 'Прокладка'), (4, 'Ребро'), (5, 'Плита'), (6, 'Лапка'), (7, 'Ребро фронтальное'), (8, 'Пластина'), (9, 'U-болт'), (10, 'Упор'), (11, 'Ребро боковое'), (12, 'Ложемент'), (13, 'Стенка'), (14, 'Кольцо'), (15, 'Кольцо направляющее'), (16, 'Труба опорная'), (17, 'Втулка'), (18, 'Патрубок'), (19, 'Фланец'), (20, 'Пружина'), (21, 'Шпилька'), (22, 'Траверса'), (23, 'Хомут'), (24, 'Пружинный блок'), (25, 'Жесткий подвес')], null=True, verbose_name='Наименование'),
        ),
        migrations.RunPython(delete_double, migrations.RunPython.noop),
    ]
