# Generated by Django 4.2 on 2023-08-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_populate_detail_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectitemrevision',
            options={'verbose_name': 'ревизия объекта', 'verbose_name_plural': 'ревизии объектов'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='children',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_revision',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='ops.item', verbose_name='Дочерний элемент')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ops.item', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'ordering': ('parent', 'position'),
            },
        ),
    ]
