# Generated by Django 4.2 on 2023-08-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_alter_projectitemrevision_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchild',
            options={'ordering': ('parent', 'position'), 'permissions': (('add_own_itemchild', 'Может создавать свою спецификацию'), ('change_own_itemchild', 'Может изменить свою спецификацию'), ('delete_own_itemchild', 'Может удалить свою спецификацию'), ('view_own_itemchild', 'Может видеть свою спецификацию')), 'verbose_name': 'Спецификация'},
        ),
    ]
