# Generated by Django 4.2 on 2023-09-18 10:25

from django.db import migrations, models


# Тут укажем лейблы с ошибками, в админке отобразятся верные
class ItemName(models.IntegerChoices):
    HALF_CLAMP = 1, 'Полухомут'
    BASE = 2, 'Основание'
    GASKET = 3, 'Прокладка'
    FIN = 4, 'Ребро'
    PLATE = 5, 'Плита'
    LEG = 6, 'Лапка'
    FRONT_FIN = 7, 'Ребро фронтальное'
    SHEET = 8, 'Пластина'
    U_BOLT = 9, 'U-болт'
    LIMIT = 10, 'Упор'
    SIDE_FIN = 11, 'Ребро боковое'
    LODGMENT = 12, 'Ложемент'
    WALL = 13, 'Стенка'
    RING = 14, 'Кольцо'
    GUIDE_RING = 15, 'Кольцо направляющее'
    SUPPORT_PIPE = 16, 'Труба опораная'
    COLLAR = 17, 'Втулка'
    BRANCH_PIPE = 18, 'Патрубок'
    FLANGE = 19, 'Фланец'
    SPRING = 20, 'Пружина'
    STUD = 21, 'Шпилька'
    TRAVERSE = 22, 'Траверса'
    CLAMP = 23, 'Хомут'
    SPRING_BLOCK = 24, 'Пружинные блоки'
    RIGID_STRUT = 25, 'Подвес жесткий'


def fill_short(apps, schema_editor):
    DetailType = apps.get_model('ops', 'DetailType')
    for item in DetailType.objects.all():
        for name in ItemName:
            if item.short_name.lower() == name.label.lower():
                item.short = name.value
                item.save()
                print(f' {item.designation} заполнен')
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_detailtype_short'),
    ]

    operations = [
        migrations.RunPython(fill_short, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='detailtype',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='detailtype',
            name='designation',
            field=models.CharField(max_length=32, unique=True, verbose_name='Обозначение'),
        ),
    ]
