# Generated by Django 4.2 on 2023-08-30 22:03

from django.db import migrations, models
import django.db.models.deletion


def populate_empty_clamp_material(apps, scheme_editor):
    DetailParameters = apps.get_model('ops', 'DetailParameters')
    Material = apps.get_model('catalog', 'Material')

    instances = DetailParameters.objects.filter(clamp_material__isnull=True)

    if instances.exists():
        material, _ = Material.objects.get_or_create(name='Безымянный материал хомута')
        instances.update(clamp_material=material)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_populate_materials'),
        ('ops', '0016_alter_itemchild_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailparameters',
            name='clamp_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.material', verbose_name='Материал хомута'),
        ),
        migrations.RunPython(populate_empty_clamp_material),
        migrations.AlterField(
            model_name='detailparameters',
            name='clamp_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='catalog.material', verbose_name='Материал хомута'),
        ),
        migrations.AddField(
            model_name='detailparameters',
            name='insert',
            field=models.FloatField(default=0, verbose_name='Вкладыш'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailparameters',
            name='pipe_mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Крепление к трубе'),
        ),
        migrations.AddField(
            model_name='detailparameters',
            name='top_mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Верхний крепление'),
        ),
    ]
