# Generated by Django 4.2 on 2023-09-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_remove_detailtype_short_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailtype',
            old_name='short',
            new_name='short_name',
        ),
    ]
