# Generated by Django 4.2 on 2023-08-30 22:36

from django.db import migrations
import pybarker.django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_detailparameters_clamp_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parameters',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Параметры'),
        ),
    ]
