# Generated by Django 4.2 on 2023-09-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_item_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование группы')),
                ('label', models.CharField(max_length=255, verbose_name='Заголовок группы')),
            ],
            options={
                'verbose_name': 'Группа атрибутов',
                'verbose_name_plural': 'Группы атрибутов',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('datetime', 'Дата/Время'), ('date', 'Дата')], max_length=255, verbose_name='Тип поля')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование поля')),
                ('label', models.CharField(max_length=255, verbose_name='Заголовок поля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание поля')),
                ('is_required', models.BooleanField(blank=True, default=False, verbose_name='Обязательное поле')),
                ('default', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение по-умолчанию')),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ops.detailtype', verbose_name='Тип детали/изделия')),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.fieldset', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
    ]
