# Generated by Django 4.2 on 2023-09-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_alter_detailtype_short_name'),
        ('ops', '0019_fieldset_attribute'),
    ]

    operations = [
    ]
