# Generated by Django 4.2 on 2023-09-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_merge_20230919_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='marking_template',
            field=models.CharField(max_length=255, null=True, verbose_name='Шаблон маркировки'),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Масса, кг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='marking',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Маркировка'),
        ),
    ]
