# Generated by Django 4.2 on 2023-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_detailtype_marking_template_item_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtype',
            name='marking_template',
            field=models.CharField(default='NONE', max_length=255, verbose_name='Шаблон маркировки'),
            preserve_default=False,
        ),
    ]
