# Generated by Django 4.2 on 2023-09-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_alter_detailtype_marking_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='marking',
            field=models.CharField(default='NONE', max_length=32, verbose_name='Маркировка'),
            preserve_default=False,
        ),
    ]
