# Generated by Django 4.2 on 2023-09-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_populate_materials'),
        ('ops', '0023_alter_item_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='load_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.loadgroup', verbose_name='Нагрузочная группа'),
        ),
    ]
