# Generated by Django 4.2 on 2023-09-26 09:40

from django.db import migrations, models
import django.db.models.deletion
import ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_alter_item_load_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, help_text='Если пустой, то сработает всегда', null=True, verbose_name='Условие')),
                ('position', models.IntegerField(default=0, help_text='От позиции зависит, порядок просмотра эскизов, чем меньше значение, тем больше приоритет', verbose_name='Позиция')),
                ('image', models.ImageField(upload_to=ops.models.upload_sketch_to, verbose_name='Изображение')),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='ops.detailtype', verbose_name='Тип детали')),
            ],
            options={
                'verbose_name': 'Эскиз',
                'verbose_name_plural': 'Эскизы',
                'ordering': ('position',),
            },
        ),
    ]
