# Generated by Django 4.2 on 2023-09-27 21:37

from django.db import migrations, models
import django.db.models.deletion
import ops.models


def populate_default_variants(apps, scheme_editor):
    DetailType = apps.get_model('ops', 'DetailType')
    Variant = apps.get_model('ops', 'Variant')

    detail_types = DetailType.objects.filter(variants__isnull=True)

    for detail_type in detail_types:
        variant = Variant.objects.create(
            detail_type=detail_type,
            name='1',
            marking_template=detail_type.marking_template,
            sketch=None,
            is_fallback=True,
        )


def populate_variants_in_attributes(apps, scheme_editor):
    Attribute = apps.get_model('ops', 'Attribute')
    Variant = apps.get_model('ops', 'Variant')

    attributes = Attribute.objects.filter(variant__isnull=True)

    for attribute in attributes:
        variant = Variant.objects.get(detail_type=attribute.detail_type)
        attribute.variant = variant

    Attribute.objects.bulk_update(attributes, fields=['variant'])


def populate_variants_in_items(apps, scheme_editor):
    Item = apps.get_model('ops', 'Item')
    Variant = apps.get_model('ops', 'Variant')

    items = Item.objects.filter(variant__isnull=True)

    for item in items:
        variant = Variant.objects.get(detail_type=item.type)
        item.variant = variant

    Item.objects.bulk_update(items, fields=['variant'])


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_sketch'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='use_variants',
            field=models.BooleanField(blank=True, default=False, verbose_name='Использовать варианты исполнения'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('marking_template', models.CharField(blank=True, max_length=255, null=True, verbose_name='Шаблон маркировки')),
                ('sketch', models.ImageField(blank=True, null=True, upload_to=ops.models.upload_sketch_to, verbose_name='Эскиз')),
                ('is_fallback', models.BooleanField(blank=True, default=False, help_text='Если в другом варианте не были обнаружены шаблон маркировки, эскиза и т.д., то будут выбраны отсюда', verbose_name='Вариант по-умолчанию')),
            ],
            options={
                'verbose_name': 'исполнение',
                'verbose_name_plural': 'исполнении',
                'ordering': ('detail_type', 'name'),
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='ops.detailtype', verbose_name='Тип детали/изделий'),
        ),
        migrations.RunPython(populate_default_variants),
        migrations.RemoveField(
            model_name='detailtype',
            name='marking_template',
        ),
        migrations.AddField(
            model_name='attribute',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='ops.variant', verbose_name='Исполнение'),
        ),
        migrations.RunPython(populate_variants_in_attributes),
        migrations.AlterField(
            model_name='attribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='ops.variant', verbose_name='Исполнение'),
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.variant', verbose_name='Исполнение'),
        ),
        migrations.RunPython(populate_variants_in_items),
        migrations.AlterField(
            model_name='item',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.variant', verbose_name='Исполнение'),
        ),
        migrations.DeleteModel(
            name='Sketch',
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'атрибут', 'verbose_name_plural': 'атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='fieldset',
            options={'verbose_name': 'группа атрибутов', 'verbose_name_plural': 'группы атрибутов'},
        ),
        migrations.AlterModelOptions(
            name='itemchild',
            options={'ordering': ('parent', 'position'), 'permissions': (('add_own_itemchild', 'Может создавать свою спецификацию'), ('change_own_itemchild', 'Может изменить свою спецификацию'), ('delete_own_itemchild', 'Может удалить свою спецификацию'), ('view_own_itemchild', 'Может видеть свою спецификацию')), 'verbose_name': 'спецификация', 'verbose_name_plural': 'спецификация'},
        ),
    ]
