# Generated by Django 4.2 on 2023-09-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_variant_alter_attribute_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='detail_type',
        ),
    ]
