# Generated by Django 4.2 on 2023-09-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_remove_attribute_detail_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='is_fallback',
        ),
    ]
