# Generated by Django 4.2 on 2023-09-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0029_populate_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtype',
            name='use_variants',
        ),
    ]
