# Generated by Django 4.2 on 2023-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0030_remove_detailtype_use_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='marking',
            field=models.CharField(max_length=255, verbose_name='Маркировка'),
        ),
    ]
