# Generated by Django 4.2 on 2023-09-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0031_alter_item_marking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('detail_type', 'name'), 'verbose_name': 'исполнение', 'verbose_name_plural': 'исполнения'},
        ),
    ]
