# Generated by Django 4.2 on 2023-10-01 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0032_alter_variant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z_]+$', 'Должен содержать только английские буквы и _')], verbose_name='Наименование поля'),
        ),
    ]
