# Generated by Django 4.2 on 2023-10-01 17:59

from django.db import migrations
import kernel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0033_alter_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='choices',
            field=kernel.fields.AttributeChoiceField(blank=True, null=True, verbose_name='Список'),
        ),
    ]
