# Generated by Django 4.2 on 2023-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0034_attribute_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='catalog',
            field=models.CharField(blank=True, choices=[('PipeDiameter', 'Диаметр трубы'), ('LoadGroup', 'Нагрузочная группа'), ('Material', 'Материал')], max_length=255, null=True, verbose_name='Справочник'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('datetime', 'Дата/Время'), ('date', 'Дата'), ('catalog', 'Справочник')], max_length=255, verbose_name='Тип поля'),
        ),
    ]
