# Generated by Django 4.2 on 2023-10-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_material_group'),
        ('ops', '0036_item_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='additional_load_x',
            field=models.FloatField(default=0, verbose_name='Дополнительная нагрузка (расчетная) X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='additional_load_y',
            field=models.FloatField(default=0, verbose_name='Дополнительная нагрузка (расчетная) Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='additional_load_z',
            field=models.FloatField(default=0, verbose_name='Дополнительная нагрузка (расчетная) Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='ambient_temperature',
            field=models.IntegerField(default=0, verbose_name='Температура среды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='clamp_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.material', verbose_name='Материал хомута'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='distance_between_supports',
            field=models.FloatField(default=0, verbose_name='Расстояние между опорами'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='estimated_state',
            field=models.CharField(choices=[('cold', 'Холодная нагрузка'), ('hot', 'Горячая нагрузка')], default='cold', max_length=4, verbose_name='Расчетное состояние'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='insert',
            field=models.FloatField(default=0, verbose_name='Вкладыш'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='insulation_thickness',
            field=models.FloatField(default=0, verbose_name='Толщина изоляции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_minus_x',
            field=models.FloatField(default=0, verbose_name='Нагрузка -X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_minus_y',
            field=models.FloatField(default=0, verbose_name='Нагрузка -Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_minus_z',
            field=models.FloatField(default=0, verbose_name='Нагрузка -Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_plus_x',
            field=models.FloatField(default=0, verbose_name='Нагрузка +X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_plus_y',
            field=models.FloatField(default=0, verbose_name='Нагрузка +Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_plus_z',
            field=models.FloatField(default=0, verbose_name='Нагрузка +Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='minimum_spring_travel',
            field=models.FloatField(default=0, verbose_name='Минимальный запас хода пружины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='move_minus_x',
            field=models.FloatField(default=0, verbose_name='Перемещение -X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='move_minus_y',
            field=models.FloatField(default=0, verbose_name='Перемещение -Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='move_minus_z',
            field=models.FloatField(default=0, verbose_name='Перемещение -Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='move_plus_x',
            field=models.FloatField(default=0, verbose_name='Перемещение +X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='move_plus_y',
            field=models.FloatField(default=0, verbose_name='Перемещение +Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='move_plus_z',
            field=models.FloatField(default=0, verbose_name='Перемещение +Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='nominal_diameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.pipediameter', verbose_name='Номинальный диаметр'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='outer_diameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.pipediameter', verbose_name='Внешний диаметр'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='outer_diameter_special',
            field=models.FloatField(blank=True, null=True, verbose_name='Внешний диаметр специальный'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='pipe_direction',
            field=models.CharField(choices=[('x', 'X'), ('y', 'Y'), ('z', 'Z'), ('at_angle', 'Под углом')], default='x', max_length=8, verbose_name='Направление трубы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='pipe_location',
            field=models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное')], default='horizontal', max_length=10, verbose_name='Расположение трубы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='pipe_mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Крепление к трубе'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='top_mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Верхний крепление'),
        ),
        migrations.DeleteModel(
            name='DetailParameters',
        ),
    ]
