# Generated by Django 4.2 on 2023-10-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0037_projectitem_additional_load_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='outer_diameter',
        ),
        migrations.RemoveField(
            model_name='projectitem',
            name='pipe_mount',
        ),
        migrations.RemoveField(
            model_name='projectitem',
            name='top_mount',
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='additional_load_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Дополнительная нагрузка (расчетная) X'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='additional_load_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Дополнительная нагрузка (расчетная) Y'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='additional_load_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Дополнительная нагрузка (расчетная) Z'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='distance_between_supports',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние между опорами'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='insert',
            field=models.FloatField(blank=True, null=True, verbose_name='Вкладыш'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='insulation_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Толщина изоляции'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='load_minus_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Нагрузка -X'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='load_minus_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Нагрузка -Y'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='load_minus_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Нагрузка -Z'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='load_plus_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Нагрузка +X'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='load_plus_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Нагрузка +Y'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='load_plus_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Нагрузка +Z'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='minimum_spring_travel',
            field=models.FloatField(default=5.0, verbose_name='Минимальный запас хода пружины'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='move_minus_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение -X'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='move_minus_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение -Y'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='move_minus_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение -Z'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='move_plus_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение +X'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='move_plus_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение +Y'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='move_plus_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение +Z'),
        ),
    ]
