# Generated by Django 4.2 on 2023-10-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_coveringtype'),
        ('ops', '0038_remove_projectitem_outer_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='catalog',
            field=models.CharField(blank=True, choices=[('NominalDiameter', 'Номинальный диаметр'), ('PipeDiameter', 'Диаметр трубы'), ('LoadGroup', 'Нагрузочная группа'), ('Material', 'Материал'), ('CoveringType', 'Тип покрытия')], max_length=255, null=True, verbose_name='Справочник'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='nominal_diameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.newpipediameter', verbose_name='Номинальный диаметр'),
        ),
    ]
