# Generated by Django 4.2 on 2023-10-11 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0039_alter_attribute_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Должен содержать только английские буквы, цифры и _')], verbose_name='Наименование поля'),
        ),
    ]
