# Generated by Django 4.2 on 2023-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0040_alter_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='calculated_value',
            field=models.CharField(blank=True, help_text='Если формула вычисления здесь указан, то поле является вычисляемым, и его нельзя будет редактировать вручную', max_length=255, null=True, verbose_name='Вычисляемое значение'),
        ),
    ]
