# Generated by Django 4.2 on 2023-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0041_attribute_calculated_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание поля'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание поля'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поля'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поля'),
        ),
        migrations.AddField(
            model_name='fieldset',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок группы'),
        ),
        migrations.AddField(
            model_name='fieldset',
            name='label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок группы'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поля'),
        ),
        migrations.AlterField(
            model_name='fieldset',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок группы'),
        ),
    ]
