# Generated by Django 4.2 on 2023-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0042_attribute_description_en_attribute_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_manual_changed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
