# Generated by Django 4.2 on 2023-10-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0043_item_name_manual_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='marking',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Маркировка'),
        ),
        migrations.AlterField(
            model_name='itemchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ops.item', verbose_name='Родитель'),
        ),
    ]
