# Generated by Django 4.2 on 2023-11-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0044_alter_item_marking_alter_itemchild_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Комплектующая базового состава',
                'verbose_name_plural': 'Комплектующие базового состава',
                'ordering': ('base_parent', 'position'),
            },
        ),
        migrations.AddField(
            model_name='projectitem',
            name='pipe_mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Крепление к трубе'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='top_mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Верхнee крепление'),
        ),
        migrations.AlterField(
            model_name='detailtype',
            name='designation',
            field=models.CharField(max_length=32, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='detailtype',
            name='short_name',
            field=models.IntegerField(choices=[(None, '--------'), (9, 'U-болт'), (17, 'Втулка'), (26, 'Жесткий подвес двойной'), (25, 'Жесткий подвес одинарный'), (14, 'Кольцо'), (15, 'Кольцо направляющее'), (6, 'Лапка'), (12, 'Ложемент'), (34, 'Опора постоянного усилия двойная'), (30, 'Опора постоянного усилия одинарная'), (2, 'Основание'), (18, 'Патрубок'), (8, 'Пластина'), (5, 'Плита'), (32, 'Подвес постоянного усилия двойной'), (28, 'Подвес постоянного усилия одинарный'), (1, 'Полухомут'), (3, 'Прокладка'), (20, 'Пружина'), (33, 'Пружинная опора двойная'), (29, 'Пружинная опора одинарная'), (24, 'Пружинный блок'), (31, 'Пружинный подвес двойной'), (27, 'Пружинный подвес одинарный'), (4, 'Ребро'), (11, 'Ребро боковое'), (7, 'Ребро фронтальное'), (13, 'Стенка'), (22, 'Траверса'), (16, 'Труба опорная'), (10, 'Упор'), (19, 'Фланец'), (23, 'Хомут'), (21, 'Шпилька')], null=True, verbose_name='Наименование'),
        ),
        migrations.AddConstraint(
            model_name='detailtype',
            constraint=models.UniqueConstraint(fields=('designation', 'category'), name='unique_detailtype'),
        ),
        migrations.AddField(
            model_name='basecomposition',
            name='base_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_children', to='ops.detailtype', verbose_name='Комплектующий узел или деталь'),
        ),
        migrations.AddField(
            model_name='basecomposition',
            name='base_parent',
            field=models.ForeignKey(limit_choices_to=models.Q(('category', 'product'), ('category', 'assembly_unit'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='base_parent', to='ops.detailtype', verbose_name='Сборка'),
        ),
    ]
