# Generated by Django 4.2 on 2023-11-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_coveringtype_description_en_and_more'),
        ('ops', '0045_basecomposition_projectitem_pipe_mount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='is_double',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Не применимо'), (0, 'Нет'), (1, 'Да')], null=True, verbose_name='Двойная?'),
        ),
        migrations.AddField(
            model_name='project',
            name='contragent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='chain_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота цепи'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='question_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ОЛ заказчика'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='test_load_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Испытательная нагрузка X'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='test_load_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Испытательная нагрузка Y'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='test_load_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Испытательная нагрузка Z'),
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_child',
            field=models.ForeignKey(limit_choices_to=models.Q(('category', 'assembly_unit'), ('category', 'detail'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='base_children', to='ops.detailtype', verbose_name='Комплектующий узел или деталь'),
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='detailtype',
            name='short_name',
            field=models.IntegerField(choices=[(None, '--------'), (9, 'U-болт'), (17, 'Втулка'), (25, 'Жесткий подвес'), (14, 'Кольцо'), (15, 'Кольцо направляющее'), (6, 'Лапка'), (12, 'Ложемент'), (28, 'Опора переменного усилия'), (29, 'Опора постоянного усилия'), (2, 'Основание'), (18, 'Патрубок'), (8, 'Пластина'), (5, 'Плита'), (26, 'Подвес переменного усилия'), (27, 'Подвес постоянного усилия'), (1, 'Полухомут'), (3, 'Прокладка'), (20, 'Пружина'), (24, 'Пружинный блок'), (4, 'Ребро'), (11, 'Ребро боковое'), (7, 'Ребро фронтальное'), (13, 'Стенка'), (22, 'Траверса'), (16, 'Труба опорная'), (10, 'Упор'), (19, 'Фланец'), (23, 'Хомут'), (21, 'Шпилька')], null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса, кг'),
        ),
        migrations.AlterField(
            model_name='itemchild',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='itemchild',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Проект CRM'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='nominal_diameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.pipediameter', verbose_name='DN'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='outer_diameter_special',
            field=models.FloatField(blank=True, null=True, verbose_name='Нестандартный диаметр'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ops.project', verbose_name='Проект CRM'),
        ),
    ]
