# Generated by Django 4.2 on 2023-11-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0046_detailtype_is_double_project_contragent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='tmp_spring',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выбранная пружина'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.item', verbose_name='Оригинальное изделие/деталь'),
        ),
        migrations.CreateModel(
            name='TemporaryComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('tmp_child', models.ForeignKey(limit_choices_to=models.Q(('category', 'assembly_unit'), ('category', 'detail'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='tmp_children', to='ops.detailtype', verbose_name='Комплектующий узел или деталь')),
                ('tmp_parent', models.ForeignKey(limit_choices_to=models.Q(('type__category', 'product'), ('type__category', 'assembly_unit'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='tmp_parent', to='ops.item', verbose_name='Сборка')),
            ],
            options={
                'verbose_name': 'Временный состав изделия',
                'verbose_name_plural': 'Временный состав изделия',
                'ordering': ('tmp_parent', 'position'),
            },
        ),
    ]
