# Generated by Django 4.2 on 2023-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0046_detailtype_is_double_project_contragent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='erp_slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='modelslug в ERP'),
        ),
        migrations.AddField(
            model_name='item',
            name='erp_id',
            field=models.CharField(blank=True, null=True, verbose_name='Идентификатор с ERP'),
        ),
    ]
