# Generated by Django 4.2 on 2023-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0047_projectitem_tmp_spring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='position_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер позиции'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='tmp_spring',
            field=models.JSONField(blank=True, null=True, verbose_name='Выбранная пружина'),
        ),
    ]
