# Generated by Django 4.2 on 2023-11-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0047_detailtype_erp_slug_item_erp_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('add_own_item', 'Может создавать свои изделия/детали/сборочные единицы'), ('change_own_item', 'Может изменить свои изделия/детали/сборочные единицы'), ('delete_own_item', 'Может удалить свои изделия/детали/сборочные единицы'), ('view_own_item', 'Может видеть свои изделия/детали/сборочные единицы'), ('sync_item_erp', 'Может синхронизировать изделия/детали/сборочные единицы в ERP')), 'verbose_name': 'Изделие/Деталь/Сборочная единица', 'verbose_name_plural': 'Изделия/Детали/Сборочные единицы'},
        ),
    ]
