# Generated by Django 4.2 on 2023-11-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_coveringtype_description_en_and_more'),
        ('ops', '0048_projectitem_position_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomposition',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='temporarycomposition',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.material', verbose_name='Материал'),
        ),
    ]
