# Generated by Django 4.2.7 on 2023-12-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0049_remove_detailtype_erp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='erp_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование поля в ERP'),
        ),
    ]
