# Generated by Django 4.2 on 2023-11-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0049_basecomposition_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtype',
            name='is_double',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '---------'), (1, 'Одинарный'), (2, 'Двойной')], null=True, verbose_name='Вид'),
        ),
    ]
