# Generated by Django 4.2 on 2023-11-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0050_alter_detailtype_is_double'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailtype',
            old_name='is_double',
            new_name='branch_qty',
        ),
    ]
