# Generated by Django 4.2 on 2023-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0051_rename_is_double_detailtype_branch_qty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detailtype',
            name='unique_detailtype',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddConstraint(
            model_name='detailtype',
            constraint=models.UniqueConstraint(fields=('designation', 'category', 'branch_qty'), name='unique_detailtype'),
        ),
        migrations.AddConstraint(
            model_name='projectitem',
            constraint=models.UniqueConstraint(fields=('project', 'position_number'), name='one_position_number_per_project'),
        ),
    ]
