# Generated by Django 4.2 on 2023-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0052_remove_detailtype_unique_detailtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='distance_between_supports',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Расстояние между опорами'),
        ),
    ]
