# Generated by Django 4.2 on 2023-11-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0053_alter_projectitem_distance_between_supports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectitem',
            old_name='distance_between_supports',
            new_name='span',
        ),
    ]
