# Generated by Django 4.2 on 2023-11-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0048_alter_item_options'),
        ('ops', '0054_rename_distance_between_supports_projectitem_span'),
    ]

    operations = [
    ]
