# Generated by Django 4.2.7 on 2023-12-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0050_attribute_erp_name'),
        ('ops', '0055_merge_20231130_1620'),
    ]

    operations = [
    ]
