# Generated by Django 4.2.7 on 2023-12-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0056_merge_20231204_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='erp_nomspec',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер спецификации'),
        ),
    ]
