# Generated by Django 4.2.7 on 2023-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0057_item_erp_nomspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='short_name_to_erp',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отправить "Наименование" в ERP'),
        ),
    ]
