# Generated by Django 4.2.7 on 2023-12-12 07:13

from django.db import migrations, models
from django.db.models import Q


def populate_erp_mapping(apps, scheme_editor):
    Attribute = apps.get_model('ops', 'Attribute')

    attributes = Attribute.objects.exclude(Q(erp_name__isnull=True) | Q(erp_name=''))

    for attribute in attributes:
        attribute.erp_name_mapping = {
            attribute.name: attribute.erp_name
        }

    Attribute.objects.bulk_update(attributes, fields=['erp_name_mapping'])


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0059_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='erp_name_mapping',
            field=models.JSONField(blank=True, null=True, verbose_name='Маппинг полей в ERP'),
        ),
        migrations.RunPython(populate_erp_mapping),
        migrations.RemoveField(
            model_name='attribute',
            name='erp_name',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='erp_name_mapping',
            new_name='erp_name',
        ),
    ]
