# Generated by Django 4.2.7 on 2023-12-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0008_alter_user_ui_config'),
        ('ops', '0060_erp_attribute_mapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('add_own_project', 'Может создавать свои проекты'), ('change_own_project', 'Может изменить свои проекты'), ('delete_own_project', 'Может удалить свои проекты'), ('view_own_project', 'Может видеть свои проекты'), ('import_project_crm', 'Может импортировать проект с CRM')), 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='kernel.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='crm_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Идентификатор из CRM'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='crm_mark_cont',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание из CRM'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='work_type',
            field=models.CharField(blank=True, choices=[('manufacturing', 'Производство'), ('refinement', 'Доработка'), ('reselling', 'Перепродажа')], max_length=13, null=True, verbose_name='Тип работ'),
        ),
        migrations.AlterField(
            model_name='projectitemrevision',
            name='project_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ops.projectitem', verbose_name='Элемент табличной части'),
        ),
    ]
