# Generated by Django 4.2.7 on 2024-03-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0061_alter_project_options_project_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ops.variant', verbose_name='Исполнение'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ops.detailtype', verbose_name='Тип детали/изделий'),
        ),
    ]
