# Generated by Django 4.2.7 on 2024-07-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0062_alter_attribute_variant_alter_variant_detail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='catalog',
            field=models.CharField(blank=True, choices=[('NominalDiameter', 'Номинальный диаметр'), ('PipeDiameter', 'Диаметр трубы'), ('LoadGroup', 'Нагрузочная группа'), ('Material', 'Материал'), ('CoveringType', 'Тип покрытия'), ('Covering', 'Покрытие')], max_length=255, null=True, verbose_name='Справочник'),
        ),
        migrations.AlterField(
            model_name='detailtype',
            name='short_name',
            field=models.IntegerField(choices=[(None, '--------'), (9, 'U-болт'), (30, 'Болты'), (31, 'Винты стопорные'), (17, 'Втулка'), (32, 'Гайки'), (25, 'Жесткий подвес'), (42, 'Заклепка'), (14, 'Кольцо'), (15, 'Кольцо направляющее'), (35, 'Кольцо стопорное'), (6, 'Лапка'), (12, 'Ложемент'), (28, 'Опора переменного усилия'), (29, 'Опора постоянного усилия'), (2, 'Основание'), (41, 'Ось'), (18, 'Патрубок'), (8, 'Пластина'), (5, 'Плита'), (26, 'Подвес переменного усилия'), (27, 'Подвес постоянного усилия'), (1, 'Полухомут'), (3, 'Прокладка'), (37, 'Прокладки'), (39, 'Проушина'), (20, 'Пружина'), (24, 'Пружинный блок'), (4, 'Ребро'), (11, 'Ребро боковое'), (7, 'Ребро фронтальное'), (13, 'Стенка'), (38, 'Талреп'), (22, 'Траверса'), (16, 'Труба опорная'), (10, 'Упор'), (19, 'Фланец'), (23, 'Хомут'), (33, 'Шайбы'), (40, 'Шильд'), (21, 'Шпилька'), (36, 'Шпильки'), (34, 'Шплинт')], null=True, verbose_name='Наименование'),
        ),
    ]
