# Generated by Django 4.2.7 on 2024-08-02 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0064_alter_detailtype_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В готовности'), ('in_progress', 'Идет'), ('success', 'Успешно'), ('error', 'Ошибка')], default='pending', max_length=11, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ops.item', verbose_name='Изделие/Деталь/Сборочная единица')),
            ],
            options={
                'verbose_name': 'ERP синхронизация',
                'verbose_name_plural': 'ERP синхронизации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('http_request', 'HttpRequest'), ('debug', 'DEBUG'), ('exception', 'Exception')], max_length=12, verbose_name='Тип лога')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Запрос')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('erp_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ops.erpsync', verbose_name='ERP синхронизация')),
            ],
            options={
                'verbose_name': 'Лог ERP синхронизации',
                'verbose_name_plural': 'Логи ERP синхронизации',
                'ordering': ['erp_sync', '-created_at'],
            },
        ),
    ]
