# Generated by Django 4.2.7 on 2024-08-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0065_erpsync_erpsynclog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpsynclog',
            options={'ordering': ['erp_sync', 'created_at'], 'verbose_name': 'Лог ERP синхронизации', 'verbose_name_plural': 'Логи ERP синхронизации'},
        ),
    ]
