# Generated by Django 4.2.7 on 2024-08-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0066_alter_erpsynclog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('add_own_project', 'Может создавать свои проекты'), ('change_own_project', 'Может изменить свои проекты'), ('delete_own_project', 'Может удалить свои проекты'), ('view_own_project', 'Может видеть свои проекты'), ('import_project_crm', 'Может импортировать проект с CRM'), ('sync_project_erp', 'Может синхронизировать проект в ERP')), 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AddField(
            model_name='erpsync',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ops.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='erpsync',
            name='type',
            field=models.CharField(choices=[('item', 'Изделие/Деталь/Сборочная единица'), ('project', 'Проект')], default='item', max_length=7, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='erpsync',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ops.item', verbose_name='Изделие/Деталь/Сборочная единица'),
        ),
    ]
