# Generated by Django 4.2.7 on 2024-09-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0068_alter_detailtype_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sketch_coords',
            field=models.JSONField(blank=True, null=True, verbose_name='Координаты эскиза'),
        ),
    ]
