# Generated by Django 4.2.7 on 2024-10-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0071_alter_detailtype_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='load_group',
        ),
    ]
