# Generated by Django 4.2.7 on 2024-11-11 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0073_alter_attribute_options_attribute_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция'),
        ),
    ]
