# Generated by Django 4.2.7 on 2024-11-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0075_rename_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'default_permissions': ('add_item', 'change_item', 'delete_item', 'view_item'), 'permissions': (('add_item', 'Может создавать изделия/детали/сборочные единицы всех пользователей'), ('change_item', 'Может изменять изделия/детали/сборочные единицы всех пользователей'), ('delete_item', 'Может удалять изделия/детали/сборочные единицы всех пользователей'), ('view_item', 'Может видеть изделия/детали/сборочные единицы всех пользователей'), ('add_own_item', 'Может создавать свои изделия/детали/сборочные единицы'), ('change_own_item', 'Может изменить свои изделия/детали/сборочные единицы'), ('delete_own_item', 'Может удалить свои изделия/детали/сборочные единицы'), ('view_own_item', 'Может видеть свои изделия/детали/сборочные единицы'), ('sync_item_erp', 'Может синхронизировать изделия/детали/сборочные единицы в ERP')), 'verbose_name': 'Изделие/Деталь/Сборочная единица', 'verbose_name_plural': 'Изделия/Детали/Сборочные единицы'},
        ),
    ]
