# Generated by Django 4.2.7 on 2024-12-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_material_options'),
        ('ops', '0076_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='clamp_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.material', verbose_name='Материал хомута'),
        ),
    ]
