# Generated by Django 4.2.7 on 2024-12-24 08:14

from django.db import migrations
import pybarker.django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0077_alter_projectitem_clamp_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchild',
            options={'ordering': ('parent', 'position'), 'permissions': (('add_own_itemchild', 'Может создавать свою спецификацию'), ('change_own_itemchild', 'Может изменить свою спецификацию'), ('delete_own_itemchild', 'Может удалить свою спецификацию'), ('view_own_itemchild', 'Может видеть свою спецификацию')), 'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификации'},
        ),
        migrations.AddField(
            model_name='item',
            name='marking_errors',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Ошибки маркировки'),
        ),
        migrations.AddField(
            model_name='item',
            name='parameters_errors',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Ошибки параметров'),
        ),
    ]
