# Generated by Django 5.1.4 on 2025-01-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0078_alter_itemchild_options_item_marking_errors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchild',
            options={'ordering': ('parent', 'position'), 'permissions': (('add_own_itemchild', 'Может создавать свою спецификацию'), ('change_own_itemchild', 'Может изменить свою спецификацию'), ('delete_own_itemchild', 'Может удалить свою спецификацию'), ('view_own_itemchild', 'Может видеть свою спецификацию')), 'verbose_name': 'спецификация', 'verbose_name_plural': 'спецификация'},
        ),
        migrations.AddField(
            model_name='projectitem',
            name='chain_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес грузовой цепи'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='cold_load',
            field=models.FloatField(blank=True, null=True, verbose_name='Холодная нагрузка'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='hot_load',
            field=models.FloatField(blank=True, null=True, verbose_name='Горячая нагрузка'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_adjustment',
            field=models.FloatField(blank=True, null=True, verbose_name='Регулировка нагрузки'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='load_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение нагрузки'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='max_move_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс. перемещение по Z'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='max_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. температура'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='min_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мин. температура'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='regulation_range_minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Диапазон регулировки "-"'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='regulation_range_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Диапазон регулировки "+"'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='spring_stiffness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жесткость пружины'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='spring_travel_down',
            field=models.IntegerField(blank=True, null=True, verbose_name='Запас хода пружины вниз'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='spring_travel_up',
            field=models.IntegerField(blank=True, null=True, verbose_name='Запас хода пружины вверх'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='tag_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег номер'),
        ),
    ]
