# Generated by Django 5.1.4 on 2025-01-09 22:44

import ops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0079_alter_itemchild_options_projectitem_chain_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='subsketch',
            field=models.ImageField(blank=True, null=True, upload_to=ops.models.upload_sketch_to, verbose_name='Дополнительный эскиз'),
        ),
        migrations.AddField(
            model_name='variant',
            name='subsketch_coords',
            field=models.JSONField(blank=True, null=True, verbose_name='Координаты дополнительного эскиза'),
        ),
    ]
