# Generated by Django 5.1.4 on 2025-01-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0080_variant_subsketch_variant_subsketch_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycomposition',
            name='lgv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LGV'),
        ),
        migrations.AddField(
            model_name='temporarycomposition',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='temporarycomposition',
            name='tag_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег номер'),
        ),
        migrations.AddField(
            model_name='temporarycomposition',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес детали'),
        ),
    ]
