# Generated by Django 5.1.4 on 2025-02-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0082_set_item_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchild',
            options={'ordering': ('parent', 'position'), 'permissions': (('add_own_itemchild', 'Может создавать свою спецификацию'), ('change_own_itemchild', 'Может изменить свою спецификацию'), ('delete_own_itemchild', 'Может удалить свою спецификацию'), ('view_own_itemchild', 'Может видеть свою спецификацию')), 'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спепцификации'},
        ),
        migrations.AddField(
            model_name='projectitem',
            name='selection_params',
            field=models.JSONField(blank=True, null=True, verbose_name='Параметры подбора'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='catalog',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Справочник'),
        ),
    ]
