# Generated by Django 5.1.4 on 2025-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0082_set_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='default_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий по умолчанию'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='catalog',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Справочник'),
        ),
    ]
