# Generated by Django 5.1.4 on 2025-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0083_alter_itemchild_options_projectitem_selection_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='system_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота системы'),
        ),
    ]
