# Generated by Django 5.1.4 on 2025-02-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0083_alter_itemchild_options_projectitem_selection_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='ambient_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Температура среды'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='pipe_direction',
            field=models.CharField(blank=True, choices=[('x', 'X'), ('y', 'Y'), ('z', 'Z'), ('at_angle', 'Под углом')], max_length=8, null=True, verbose_name='Направление трубы'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='pipe_location',
            field=models.CharField(blank=True, choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное')], max_length=10, null=True, verbose_name='Расположение трубы'),
        ),
    ]
