# Generated by Django 5.1.4 on 2025-02-11 06:41

import django.db.models.deletion
from django.db import migrations, models


def create_product_families(apps, schema_editor):
    ProductFamily = apps.get_model('catalog', 'ProductFamily')
    DetailType = apps.get_model('ops', 'DetailType')

    # Маппинг ItemName -> ProductFamily
    item_name_mapping = {
        1: "Полухомут",
        2: "Основание",
        3: "Прокладка",
        4: "Ребро",
        5: "Плита",
        6: "Лапка",
        7: "Ребро фронтальное",
        8: "Пластина",
        9: "U-болт",
        10: "Упор",
        11: "Ребро боковое",
        12: "Ложемент",
        13: "Стенка",
        14: "Кольцо",
        15: "Кольцо направляющее",
        16: "Труба опорная",
        17: "Втулка",
        18: "Патрубок",
        19: "Фланец",
        20: "Пружина",
        21: "Шпилька",
        22: "Траверса",
        23: "Хомут",
        24: "Пружинный блок",
    }

    # Создаем ProductFamily
    product_family_objects = []
    for key, value in item_name_mapping.items():
        product_family_objects.append(ProductFamily(name=value))
    ProductFamily.objects.bulk_create(product_family_objects)

    # Обновляем DetailType
    for detail in DetailType.objects.all():
        if detail.short_name in item_name_mapping:
            family = ProductFamily.objects.filter(name=item_name_mapping[detail.short_name]).first()
            if family:
                detail.product_family = family
                detail.save(update_fields=['product_family'])


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0030_productfamily'),
        ('ops', '0084_projectitem_system_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='product_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='details', to='catalog.productfamily',
                                    verbose_name='Семейство изделий'),
        ),
    ]
