# Generated by Django 5.1.4 on 2025-02-10 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_directory_display_name_template_and_more'),
        ('ops', '0084_alter_projectitem_ambient_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='nominal_diameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.pipediameter', verbose_name='DN'),
        ),
    ]
