# Generated by Django 5.1.4 on 2025-02-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0083_detailtype_default_comment_alter_attribute_catalog'),
        ('ops', '0085_alter_projectitem_nominal_diameter'),
        ('ops', '0085_detailtype_product_family'),
    ]

    operations = [
    ]
