# Generated by Django 5.1.4 on 2025-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0086_merge_20250212_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='standard',
            field=models.PositiveSmallIntegerField(choices=[(1, 'РФ'), (2, 'EN')], default=1, verbose_name='Стандарт'),
        ),
    ]
