# Generated by Django 5.1.4 on 2025-02-18 04:05

import pybarker.django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0088_detailtype_remove_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='item',
            name='height_errors',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Ошибки расчета высоты'),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_errors',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Ошибки расчета веса'),
        ),
        migrations.AddField(
            model_name='variant',
            name='formula_height',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Формула для расчета высоты'),
        ),
        migrations.AddField(
            model_name='variant',
            name='formula_weight',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Формула для расчета веса'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
