# Generated by Django 5.1.4 on 2025-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0088_detailtype_remove_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtype',
            name='technical_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Технические требования'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='full_technical_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Полные технические требования'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='technical_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Технические требования'),
        ),
    ]
