# Generated by Django 5.1.4 on 2025-02-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0089_detailtype_technical_requirements_and_more'),
        ('ops', '0089_item_height_item_height_errors_item_weight_errors_and_more'),
    ]

    operations = [
    ]
