# Generated by Django 5.1.4 on 2025-02-27 12:57

import pybarker.django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0090_merge_20250220_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chain_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес грузовой цепи'),
        ),
        migrations.AddField(
            model_name='item',
            name='chain_weight_errors',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Ошибки расчета веса грузовой цепи'),
        ),
        migrations.AddField(
            model_name='item',
            name='spring_block_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Монтажная длина пружинного блока'),
        ),
        migrations.AddField(
            model_name='item',
            name='spring_block_length_errors',
            field=pybarker.django.db.models.fields.json.ReadableJSONField(blank=True, null=True, verbose_name='Ошибки расчета монтажной длины пружинного блока'),
        ),
        migrations.AddField(
            model_name='variant',
            name='formula_chain_weight',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Формула расчёта веса грузовой цепи'),
        ),
        migrations.AddField(
            model_name='variant',
            name='formula_spring_block',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Формула расчёта монтажной длины пружинного блока в холодном состоянии'),
        ),
    ]
