# Generated by Django 5.1.4 on 2025-03-03 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_pipemountinggroup_and_more'),
        ('ops', '0091_item_chain_weight_item_chain_weight_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='pipe_mounting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.pipemountinggroup', verbose_name='Группа креплений к трубе'),
        ),
    ]
