# Generated by Django 5.1.4 on 2025-03-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0093_attribute_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='pipe_mounting_group',
        ),
    ]
