# Generated by Django 5.1.4 on 2025-03-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0094_remove_variant_pipe_mounting_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecomposition',
            name='material',
        ),
    ]
