# Generated by Django 5.1.4 on 2025-03-07 04:10

import django.db.models.deletion
from django.db import migrations, models


def populate_variants(apps, scheme_editor):
    BaseComposition = apps.get_model('ops', 'BaseComposition')

    composition_objs = BaseComposition.objects.all()
    print(composition_objs.count())

    for composition in composition_objs:
        print("BaseComposition.id:", composition.id)
        detail_type1 = composition.base_parent
        detail_type2 = composition.base_child

        variant1 = detail_type1.variants.first()
        variant2 = detail_type2.variants.first()

        if not variant1 or not variant2:
            composition.delete()
            continue

        composition.new_base_parent = variant1
        composition.new_base_child = variant2
        composition.save()

        BaseComposition.objects.get(id=composition.id)
        print(composition.new_base_parent)
        print(composition.new_base_child)


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0095_remove_basecomposition_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomposition',
            name='new_base_child',
            field=models.ForeignKey(null=True, limit_choices_to=models.Q(('detail_type__category', 'assembly_unit'), ('detail_type__category', 'detail'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='base_children', to='ops.variant', verbose_name='Комплектующий узел или деталь'),
        ),
        migrations.AddField(
            model_name='basecomposition',
            name='new_base_parent',
            field=models.ForeignKey(null=True, limit_choices_to=models.Q(('detail_type__category', 'product'), ('detail_type__category', 'assembly_unit'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='base_parent', to='ops.variant', verbose_name='Сборка'),
        ),
        migrations.RunPython(populate_variants),
        migrations.RemoveField(
            model_name='basecomposition',
            name='base_child',
        ),
        migrations.RemoveField(
            model_name='basecomposition',
            name='base_parent',
        ),
        migrations.RenameField(
            model_name='basecomposition',
            old_name='new_base_child',
            new_name='base_child',
        ),
        migrations.RenameField(
            model_name='basecomposition',
            old_name='new_base_parent',
            new_name='base_parent',
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_child',
            field=models.ForeignKey(limit_choices_to=models.Q(('detail_type__category', 'assembly_unit'), ('detail_type__category', 'detail'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='base_children', to='ops.variant', verbose_name='Комплектующий узел или деталь'),
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_parent',
            field=models.ForeignKey(limit_choices_to=models.Q(('detail_type__category', 'product'), ('detail_type__category', 'assembly_unit'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='base_parent', to='ops.variant', verbose_name='Сборка'),
        ),
    ]
