# Generated by Django 5.1.4 on 2025-03-25 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0097_alter_attribute_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomposition',
            name='base_child_detail_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category', 'assembly_unit'), ('category', 'detail'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Комплектующий узел или деталь (DetailType)'),
        ),
        migrations.AddField(
            model_name='basecomposition',
            name='base_parent_detail_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category', 'product'), ('category', 'assembly_unit'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.detailtype', verbose_name='Сборка (DetailType)'),
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_child',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('detail_type__category', 'assembly_unit'), ('detail_type__category', 'detail'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_children', to='ops.variant', verbose_name='Комплектующий узел или деталь (Variant)'),
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_parent',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('detail_type__category', 'product'), ('detail_type__category', 'assembly_unit'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_parent', to='ops.variant', verbose_name='Сборка (Variant)'),
        ),
    ]
