# Generated by Django 5.1.4 on 2025-03-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0098_basecomposition_base_child_detail_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='detail_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ops.detailtype', verbose_name='Тип детали'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ops.variant', verbose_name='Исполнение'),
        ),
    ]
