# Generated by Django 5.1.4 on 2025-03-25 03:40

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0099_attribute_detail_type_alter_attribute_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecomposition',
            old_name='base_parent',
            new_name='base_parent_variant',
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_parent_variant',
            field=models.ForeignKey(
                null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_parent',
                to='ops.variant', verbose_name='Сборка (Исполнение)'),
        ),
        migrations.RenameField(
            model_name='basecomposition',
            old_name='base_child',
            new_name='base_child_variant',
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_child_variant',
            field=models.ForeignKey(
                null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_children',
                to='ops.variant', verbose_name='Комплектующий узел или деталь (Исполнение)'),
        ),
        migrations.RenameField(
            model_name='basecomposition',
            old_name='base_parent_detail_type',
            new_name='base_parent',
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_parent',
            field=models.ForeignKey(
                limit_choices_to=models.Q(('category', 'assembly_unit'), ('category', 'detail'), _connector='OR'),
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_parent',
                to='ops.detailtype', verbose_name='Сборка'),
        ),
        migrations.RenameField(
            model_name='basecomposition',
            old_name='base_child_detail_type',
            new_name='base_child',
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_child',
            field=models.ForeignKey(
                limit_choices_to=models.Q(('category', 'assembly_unit'), ('category', 'detail'), _connector='OR'),
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_children',
                to='ops.detailtype', verbose_name='Комплектующий узел или деталь'),
        ),
    ]
