# Generated by Django 5.1.4 on 2025-03-25 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0102_altering_basecomposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='usage',
            field=models.CharField(choices=[('custom', 'Произвольный атрибут'), ('system_height', 'Используется для подсчета высоты системы'), ('connection_size', 'Присоединительный размер'), ('min_length', 'Минимальная длина'), ('system_weight', 'Используется для расчета веса'), ('f_initial', 'Усилие, когда пружина полностью разжата'), ('e_initial', 'Монтажная длина корпуса в разжатом состоянии'), ('dn', 'DN'), ('load_group', 'Нагрузочная группа'), ('length', 'Длина'), ('thickness', 'Толщина')], default='custom', max_length=15, verbose_name='Использование атрибута'),
        ),
        migrations.AlterField(
            model_name='basecomposition',
            name='base_parent',
            field=models.ForeignKey(limit_choices_to=models.Q(('category', 'product'), ('category', 'assembly_unit'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='base_parent', to='ops.detailtype', verbose_name='Сборка'),
        ),
    ]
