# Generated by Django 5.1.4 on 2025-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0103_alter_attribute_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='catalog',
            field=models.CharField(blank=True, choices=[('NominalDiameter', 'Номинальный диаметр'), ('PipeDiameter', 'Диаметр трубы'), ('LoadGroup', 'Нагрузочная группа'), ('Material', 'Материал'), ('CoveringType', 'Тип покрытия'), ('Covering', 'Покрытие'), ('SupportDistance', 'Расстояние между опорами')], max_length=15, null=True, verbose_name='Справочник'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('datetime', 'Дата/Время'), ('date', 'Дата'), ('catalog', 'Справочник')], max_length=8, verbose_name='Тип поля'),
        ),
    ]
