# Generated by Django 5.1.4 on 2025-05-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0104_alter_attribute_catalog_alter_attribute_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('add_own_project', 'Может создавать свои проекты'), ('change_own_project', 'Может изменить свои проекты'), ('delete_own_project', 'Может удалить свои проекты'), ('view_own_project', 'Может видеть свои проекты'), ('import_project_crm', 'Может импортировать проект с CRM'), ('sync_project_erp', 'Может синхронизировать проект в ERP')), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='contragent',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='usage',
            field=models.CharField(choices=[('custom', 'Произвольный атрибут'), ('system_height', 'Используется для подсчета высоты системы'), ('connection_size', 'Присоединительный размер'), ('min_length', 'Минимальная длина'), ('system_weight', 'Используется для расчета веса'), ('f_initial', 'Усилие, когда пружина полностью разжата'), ('e_initial', 'Монтажная длина корпуса в разжатом состоянии'), ('dn', 'DN'), ('load_group', 'Нагрузочная группа'), ('length', 'Длина'), ('thickness', 'Толщина'), ('size', 'Типоразмер'), ('rated_stroke', 'Номинальный ход'), ('installation_size', 'Монтажный размер')], default='custom', max_length=17, verbose_name='Использование атрибута'),
        ),
        migrations.AlterField(
            model_name='project',
            name='load_unit',
            field=models.CharField(choices=[('kN', 'kN')], max_length=2, verbose_name='Единица измерения: Нагрузка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='move_unit',
            field=models.CharField(choices=[('mm', 'mm')], max_length=2, verbose_name='Единица измерения: Перемещение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('deleted', 'Удалён')], default='draft', max_length=7, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='temperature_unit',
            field=models.CharField(choices=[('C', 'C'), ('F', 'F')], max_length=1, verbose_name='Единица измерения: Температура'),
        ),
    ]
