# Generated by Django 5.1.4 on 2025-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0105_alter_project_options_remove_project_contragent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='basecomposition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='detailtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='erpsync',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='erpsynclog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='fieldset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='itemchild',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='projectitemrevision',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='temporarycomposition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
    ]
