# Generated by Django 5.1.4 on 2025-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0106_attribute_deleted_at_basecomposition_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='series',
            field=models.CharField(blank=True, choices=[('standard_series', 'Standard Series'), ('l_series', 'L Series')], max_length=15, null=True, verbose_name='Серия'),
        ),
    ]
