# Generated by Django 5.1.4 on 2025-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_alter_componentgroup_group_type_and_more"),
        ("ops", "0110_alter_attribute_usage"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="detailtype",
            name="unique_detailtype",
        ),
        migrations.AddConstraint(
            model_name="detailtype",
            constraint=models.UniqueConstraint(
                fields=("designation", "category", "branch_qty", "deleted_at"),
                name="unique_detailtype",
            ),
        ),
    ]
