# Generated by Django 5.1.4 on 2025-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0111_remove_detailtype_unique_detailtype_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                fields=("deleted_at", "name", "detail_type"), name="unique_variant"
            ),
        ),
    ]
