# Generated by Django 5.1.4 on 2025-07-04 04:46

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0052_alter_clampmaterialcoefficient_options"),
        ("ops", "0112_variant_unique_variant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="inner_id",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name="Внутренний идентификатор",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("inner_id", "deleted_at"), name="unique_inner_id_not_deleted"
            ),
        ),
    ]
