# Generated by Django 5.1.4 on 2025-07-08 11:05

import pybarker.django.db.models.fields.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0113_alter_item_inner_id_item_unique_inner_id_not_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="locked_parameters",
            field=pybarker.django.db.models.fields.json.ReadableJSONField(
                blank=True, null=True, verbose_name="Заблокированные параметры"
            ),
        ),
    ]
