# Generated by Django 5.1.4 on 2025-07-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0114_item_locked_parameters"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectitem",
            name="one_position_number_per_project",
        ),
    ]
