# Generated by Django 5.1.4 on 2025-07-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0066_alter_ssgcatalog_options_and_more"),
        ("ops", "0116_alter_attribute_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectitem",
            name="product_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.productfamily",
                verbose_name="Семейство изделий",
            ),
        ),
    ]
