# Generated by Django 5.1.4 on 2025-08-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0117_change_items_pipediameter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={
                "default_permissions": (),
                "ordering": ["variant", "position"],
                "permissions": (
                    ("view_attribute", "Может просматривать атрибуты"),
                    ("change_attribute", "Может изменять атрибуты"),
                    ("delete_attribute", "Может удалять атрибуты"),
                    ("add_attribute", "Может добавлять атрибуты"),
                ),
                "verbose_name": "Атрибут",
                "verbose_name_plural": "Атрибуты",
            },
        ),
        migrations.AlterModelOptions(
            name="basecomposition",
            options={
                "default_permissions": (),
                "ordering": ("base_parent", "position"),
                "permissions": (
                    ("view_basecomposition", "Может просматривать базовые составы"),
                    ("change_basecomposition", "Может изменять базовые составы"),
                    ("delete_basecomposition", "Может удалять базовые составы"),
                    ("add_basecomposition", "Может добавлять базовые составы"),
                ),
                "verbose_name": "Комплектующая базового состава",
                "verbose_name_plural": "Комплектующие базового состава",
            },
        ),
        migrations.AlterModelOptions(
            name="detailtype",
            options={
                "default_permissions": (),
                "permissions": (
                    ("view_detailtype", "Может просматривать типы деталей/изделий"),
                    ("add_detailtype", "Может добавлять типы деталей/изделий"),
                    ("change_detailtype", "Может изменять типы деталей/изделий"),
                    ("delete_detailtype", "Может удалять типы деталей/изделий"),
                ),
                "verbose_name": "Тип детали/изделия",
                "verbose_name_plural": "Типы деталей/изделии",
            },
        ),
        migrations.AlterModelOptions(
            name="erpsync",
            options={
                "default_permissions": (),
                "ordering": ["-created_at"],
                "permissions": (
                    ("view_erpsync", "Может просматривать ERP синхронизации"),
                    ("change_erpsync", "Может изменять ERP синхронизации"),
                    ("delete_erpsync", "Может удалять ERP синхронизации"),
                    ("add_erpsync", "Может добавлять ERP синхронизации"),
                ),
                "verbose_name": "ERP синхронизация",
                "verbose_name_plural": "ERP синхронизации",
            },
        ),
        migrations.AlterModelOptions(
            name="erpsynclog",
            options={
                "default_permissions": (),
                "ordering": ["erp_sync", "created_at"],
                "permissions": (
                    ("view_erpsynclog", "Может просматривать логи ERP синхронизации"),
                    ("change_erpsynclog", "Может изменять логи ERP синхронизации"),
                    ("delete_erpsynclog", "Может удалять логи ERP синхронизации"),
                    ("add_erpsynclog", "Может добавлять логи ERP синхронизации"),
                ),
                "verbose_name": "Лог ERP синхронизации",
                "verbose_name_plural": "Логи ERP синхронизации",
            },
        ),
        migrations.AlterModelOptions(
            name="fieldset",
            options={
                "default_permissions": (),
                "permissions": (
                    ("view_fieldset", "Может просматривать группы атрибутов"),
                    ("change_fieldset", "Может изменять группы атрибутов"),
                    ("delete_fieldset", "Может удалять группы атрибутов"),
                    ("add_fieldset", "Может добавлять группы атрибутов"),
                ),
                "verbose_name": "группа атрибутов",
                "verbose_name_plural": "группы атрибутов",
            },
        ),
        migrations.AlterModelOptions(
            name="itemchild",
            options={
                "default_permissions": (),
                "ordering": ("parent", "position"),
                "permissions": (
                    (
                        "add_itemchild",
                        "Может создавать любые спецификации любой изделия/детали/сборочной единицы",
                    ),
                    (
                        "change_itemchild",
                        "Может изменять любые спецификации любой изделия/детали/сборочной единицы",
                    ),
                    (
                        "delete_itemchild",
                        "Может удалять любые спецификации любой изделия/детали/сборочной единицы",
                    ),
                    (
                        "view_itemchild",
                        "Может видеть любые спецификации любой изделия/детали/сборочной единицы",
                    ),
                    (
                        "add_own_itemchild",
                        "Может создавать спецификацию для своего изделия/детали/сборочной единицы",
                    ),
                    (
                        "change_own_itemchild",
                        "Может изменять спецификацию для своего изделия/детали/сборочной единицы",
                    ),
                    (
                        "delete_own_itemchild",
                        "Может удалять спецификацию для своего изделия/детали/сборочной единицы",
                    ),
                    (
                        "view_own_itemchild",
                        "Может видеть спецификацию для своего изделия/детали/сборочной единицы",
                    ),
                ),
                "verbose_name": "Спецификация",
                "verbose_name_plural": "Спепцификации",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_project", "Может создавать проекты для любого пользователя"),
                    ("change_project", "Может изменять проекты любого пользователя"),
                    ("delete_project", "Может удалять проекты любого пользователя"),
                    ("view_project", "Может видеть проекты любого пользователя"),
                    ("add_own_project", "Может создавать проекты"),
                    ("change_own_project", "Может изменить собственные проекты"),
                    ("delete_own_project", "Может удалить собственные проекты"),
                    ("view_own_project", "Может видеть собственные проекты"),
                    ("import_project_crm", "Может импортировать проект с CRM"),
                    ("sync_project_erp", "Может синхронизировать проект в ERP"),
                ),
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AlterModelOptions(
            name="projectitem",
            options={
                "default_permissions": (),
                "permissions": (
                    ("view_projectitem", "Может просматривать табличную часть проекта"),
                    (
                        "add_projectitem",
                        "Может добавлять элементы в табличную часть проекта",
                    ),
                    (
                        "change_projectitem",
                        "Может изменять элементы табличной части проекта",
                    ),
                    (
                        "delete_projectitem",
                        "Может удалять элементы из табличной части проекта",
                    ),
                ),
                "verbose_name": "Табличная часть проекта",
                "verbose_name_plural": "Табличная часть проекта",
            },
        ),
        migrations.AlterModelOptions(
            name="projectitemrevision",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "view_projectitemrevision",
                        "Может просматривать ревизии объектов табличной части проекта",
                    ),
                    (
                        "add_projectitemrevision",
                        "Может добавлять ревизии объектов табличной части проекта",
                    ),
                    (
                        "change_projectitemrevision",
                        "Может изменять ревизии объектов табличной части проекта",
                    ),
                    (
                        "delete_projectitemrevision",
                        "Может удалять ревизии объектов табличной части проекта",
                    ),
                ),
                "verbose_name": "Ревизия объекта",
                "verbose_name_plural": "Ревизии объектов",
            },
        ),
        migrations.AlterModelOptions(
            name="variant",
            options={
                "default_permissions": (),
                "ordering": ("detail_type", "name"),
                "permissions": (
                    ("view_variant", "Может просматривать исполнения"),
                    ("add_variant", "Может добавлять исполнения"),
                    ("change_variant", "Может изменять исполнения"),
                    ("delete_variant", "Может удалять исполнения"),
                ),
                "verbose_name": "исполнение",
                "verbose_name_plural": "исполнения",
            },
        ),
    ]
