# Generated by Django 5.1.4 on 2025-08-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0117_change_items_pipediameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='move_minus_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение -угловое (градусы)'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='move_plus_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Перемещение +угловое (градусы)'),
        ),
    ]
