# Generated by Django 5.1.4 on 2025-08-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0118_alter_attribute_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "default_permissions": (),
                "permissions": (
                    ("add_project", "Может создавать проекты для любого пользователя"),
                    ("change_project", "Может изменять проекты любого пользователя"),
                    ("delete_project", "Может удалять проекты любого пользователя"),
                    ("view_project", "Может видеть проекты любого пользователя"),
                    ("add_own_project", "Может создавать проекты"),
                    ("change_own_project", "Может изменить собственные проекты"),
                    ("delete_own_project", "Может удалить собственные проекты"),
                    ("view_own_project", "Может видеть собственные проекты"),
                    ("view_org_project", "Может видеть проекты своей организации"),
                    ("change_org_project", "Может изменять проекты своей организации"),
                    ("delete_org_project", "Может удалять проекты своей организации"),
                    ("import_project_crm", "Может импортировать проект с CRM"),
                    ("sync_project_erp", "Может синхронизировать проект в ERP"),
                ),
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
