# Generated by Django 5.1.4 on 2025-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0119_alter_project_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailtype",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="detail_types/", verbose_name="Иконка"
            ),
        ),
    ]
