# Generated by Django 5.1.4 on 2025-08-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0118_projectitem_move_minus_d_projectitem_move_plus_d'),
        ('ops', '0120_detailtype_icon'),
    ]

    operations = [
    ]
