# Generated by Django 5.1.4 on 2025-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0121_merge_20250829_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="usage",
            field=models.CharField(
                choices=[
                    ("custom", "Произвольный атрибут"),
                    ("system_height", "Используется для подсчета высоты системы"),
                    ("connection_size", "Присоединительный размер"),
                    ("min_length", "Минимальная длина"),
                    ("system_weight", "Используется для расчета веса"),
                    ("f_initial", "Усилие, когда пружина полностью разжата"),
                    (
                        "e_initial",
                        "Монтажная длина корпуса в сжатом (рабочем) состоянии",
                    ),
                    ("dn", "DN"),
                    ("load_group", "Нагрузочная группа"),
                    ("load", "Нагрузка"),
                    ("length", "Длина"),
                    ("thickness", "Толщина"),
                    ("size", "Типоразмер"),
                    ("rated_stroke", "Номинальный ход"),
                    ("installation_size", "Пролет"),
                    ("pipe_diameter", "Диаметр трубы"),
                ],
                default="custom",
                max_length=17,
                verbose_name="Использование атрибута",
            ),
        ),
    ]
