# Generated by Django 5.1.4 on 2025-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0122_alter_attribute_usage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailtype",
            name="icon",
        ),
        migrations.AddField(
            model_name="variant",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="variants/", verbose_name="Иконка"
            ),
        ),
    ]
