# Generated by Django 5.1.4 on 2025-09-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0117_projectitem_product_family"),
        ("ops", "0123_remove_detailtype_icon_variant_icon"),
    ]

    operations = []
